#Main.jsp
#Menu
direction=ltr
align=left
logout=LogOut
home=Home Page
info=My Info
bookmark=Bookmark
calender=Calender
listfolder=MyFolders
changpass=Change Password
withdcall=Withdraw Call
myworks=My Activities
mycomments=MyComments
myappointments=MyAppointments
choose=Choose
changecamp=Change Default Campaign
changeview=Change Default View
curruser=Current User
manggroup=Managment Group
lastsign=Last SignIn
company=Company Name

#ShowFolders.jsp
myfolders=My Folders
nofolders=There are no files to follow up

#search_for_my_activity.jsp
search=Search
searchmywork=Find My Works
fromdate=From
todate=To 
status=Status
noresults=No Results
followno=Follow-Up No
clientname=Client Name 
request=Request
recode=Request Code 
source=Source
date=Status Date 

#Client_comments.jsp
clientscomments=Clients Comments
comments=Comments
comment=Comment
commentdate=Date
employee=Employee
addcomment=Add Comment
clientcode=Client Code
mobile=Mobile
intnumber=International No.
mail=Mail
all=All
commentadded=The Comment is added Successfully
commenttype=Comment Type
ceneralcomment=General
privatecomment=Private
viewcomments=View Comments

dep = Department
campaign=Campaign
projects=Projects
entryDate=Entry Date

rate=Classification
paymentPlans = Payment Plans
subject=Subject
newClient=New Client