# Sample ResourceBundle properties file


menulisting=Menu 
select=Select
selected=Selected

groupname=Group Name
groupdescription=Group Description
group=Group

username=User Name
password=Password
email=Email Address

accountname=Folder Name
accounttitle=Folder Name
accountdescription=Folder Description

classname=Classification Name
classdescription=Classification Description

itemtitle=Configuration Item Name
foraccount=For Folder
classification=Classification
classtitle=Classification Name
itemdescription=Configuration Item Description

user=User
group=Group
userlist=User List
grouplist=Group List
groupmembers=Group Members

accountlist=Folder List
classlist=Classification List

accountitenlist=Separator List
splash=Document Management System

cancel=Cancel
backtolist=&#1575;&#1604;&#1593;&#1608;&#1583;&#1607; &#1573;&#1604;&#1609; &#1575;&#1604;&#1602;&#1575;&#1574;&#1605;&#1577;

viewuser=View Existing User
viewgroup=View Existing Group
viewaccount=View Folder
viewbusinessclass=View Business Class

saveitem=Save
saveclass=Save
saveaccount=Save
saveuser=Save
savegroup=Save

addaccountitem=New Configuration Item
addclass=New Classification
addaccount=New Folder
adduser=New User


assgroupmenu=Assign group Menu
usercreationstatus=Creation Status
groupcreationstatus=Creation Status
accountsavestatus=Save Status
classsavestatus=Save Status
accountitemsavestatus=Save Status

delteaccount= Delete
areyousure=Are You Sure?
deleteclass=Delete
deletegroup=Delete
deleteuser=Delete

updateexistinguser=Update
updateuser=Update
userupdatestatus=Update Status
updateexistinggroup=Update
updategroup=Update
groupupdatestatus=update status

login=Login
invalidinfo=Invalid Information
userloggedon=user is already logged on system

atlimit=Max user number has been reached
dbbackup = Database Backup
startbackup = Start Backup
filepath = File Path
syscabinet = System Cabinet
activedocs = Active Documents
typename = Document Type Name
typedescription = Document Type Description
newtype = New Document Type
newfolder = New Folder
#edit folder
editfldr=Edit Folder

#ok
updateok=Done

#view separator
separatordlts=View Separator 

#view document
viewdoc=View Document Type

#edit document
editdoctype=Edit Document Type

fldrwarning=Warning\: Deleting this folder will also delete all related separators, documents and bookmarks

sptrwarning=Warning\: Deleting this separator will also delete all related documents and bookmarks

documentsearch=Document Search

search=Search

documentid=Document ID

nodocument=No Document With Such ID

systemid=System Identification

docdate=Folder Date

facevalue=Face Value

createdby=Created By

creationdate=Creation Date

sepdate=Separator Date

publishtype=Publish Document

confirmselection=Confirm Selection

documenttype=Publish Type

configitemtype=Configuration Item Type

trcname=Influenced Name

trcId=Influenced Id

InfType=Traceability Type

tracType=Traceability Direction

createdbyname=Created By Name


groupName=Group 

versionnumber=Version Number
