#Seasons_list.jsp
textalign=left
direction=ltr
name=Name
view=View
edit=Edit
delete=Delete
tools=Tools
 comm_channel_attribute_name = englishName
campcount=Campaigns No.
 addtool = Add Tool
viewtool =  View Tools
 arabicNameMsg = Arabic name is required
  englishNameMsg = English name is required
 successMsg = Saved Successfully
 failMsg = Client Is On This Campaign 
addClients=Add Clients to the Campaign 
selectOneClient=Select at least one client to save.
moveClients=Move Clients to Another Campaign
tableTitle=Clients of Campaign
expenses=Expenses
addExpense=Add Expense
company=Company
select=Select
expenseDate=Expense Date
amount=Amount
currency=Currency
dollar=Dollar
pound=Pound

#View_Season_Type
 pagetitle  = View Campaign Type
english_name = English Name
camp_code = Code
arabic_name = Arabic Name
back = Back 
success_Status = Season Saved Successfully
fail_Status = Fail To Save This Season
display=Display

#Update_Season_Type.jsp
updatetittle=Update Season
update=Update
supdate_Status= Updated Successfully
fupdate_Status=Fail To Update 

#Confirm_Delete_Season_Type.jsp
deletetittle=Delete Season
sdelete_Status=Season deleted Successfully
fdelete_Status=Fail To delete This Season

#tools_list.jsp
permenant=Permenant 
yes=Yes
no=No

#tool_form.jsp
channel=Communication Channel

#record_Seasons_List.jsp
PL = Record Seasons List
PN=Record Seasons  No.
viewrecordtittle=View Record Season
ssave_record_Status =  Fail To Save This Record Season 
fsave_record_Status =  Record Season Saved Successfully
forever = Forever

#update_record_season.jsp
updaterecordtittle=Update Record Season

#campaigns_list.jsp
campaigns=Campaigns

#view_Campaign.jsp
 campaignTitle =  Campaign Code
 subCampaignCode =  Sub Campaign Code
  saveButtonLabel =  Save  
 sStatus =  Campaign Saved Successfully 
 fStatus =  Fail To Save This Campaign 
 fromDate = Start Date
 toDate =  End Date 
 approximateCost =  Approximate Cost 
 objective =  Calls Targeted 
 toolID =  Tool ID 
 projects =  Projects 
 directioncall =  Direction 
 forward = Outbound 
 backward = Inbound 
both= Recycle 
donedeleted=Deleted Successfully 
fdelete_Status= Campaign Has Clients - Can`t Remove
ssavestatus=Saved Successfully 
fsavestatus=Failed To Save
save=Save
camptittle=Please Enter the tittle of the Campaign
campfromdate=Please Enter the value of From Date 
camptodate=Please Enter the value of To Date 
campapproximateCost=Please Enter the value of Approximate Cost 
daterangeerror=To Date must be greater than From Date
costerror=Please Enter a valid value for the approximate cost
projectserror=Please choose the projects
totalSubCostError=Total cost for sub campaigns must not be greater than cost for main campaign

#campaigns_load.jsp
choosecamp=choose campaign 
campaignname=Campaign Name
prjname = Project Name
allPrj = All
campaigns_loadtittle=Clients Campaign Report
nodata=No Data
clientcode=Client Code
clientname=Client Name
source=Source
resp=Responsible
 print = Show Report
camperror=Please Select a Campaign
deleteSelectMsg=Select at least one client

#client_incentives
 clientincentives = Clients' Incentives
clienttittle=Client

#internal_appointments
phone=Phone
mobile=Mobile
date=Follow-up Date
comment=Comment
interPhone=Inter. Phone

# existing clients
inDate=In Date
existingClients=Re-entered Clients
deleteExpense=Delete
deleteMsg=Delete, are you sure?
customerReferral=Customer Referral
clientsCount=Number of Clients
totalClients=Total Clients
companyRequiredMsg=Select Company
synchronizeTools=Synchronize Campaign Tools
euro=Euro
paidAmount=Paid Amount
exchangeRate=Exchange Rate
expenseDateRequiredMsg=Select Date
currencyTypeRequiredMsg=Select Currency
paidAmountRequiredMsg=Enter Paid Amount
exchangeRateRequiredMsg=Enter Exchange Rate
group = Group
campaign=Campaign Name
xAlign=right
deleteClients=Separate Clients From Campaign
show=Show
clientExistsMsg=Clients exists, proceed deleting?
totalCost=Total Cost
secondaryCampaign=secondary campaign
changeCampaignTool=Change Campaign Tool
changeCampaignCode=Change Campaign Code
changeCampaignCost=Change Campaign Cost
campaignStatus=Status
changeCampaignStatus=Activate Status