CREATE UNIQUE INDEX CLIENT_IDENTIFIER ON CLIENT (NAME,MOBILE);

ALTER TABLE DISTRIBUTION_LIST DROP CONSTRAINT DISTRIBUTION_COMPLAINTS_FK;
ALTER TABLE DISTRIBUTION_LIST ADD CONSTRAINT DISTRIBUTION_COMPLAINTS_FK FOREIGN KEY (CLIENT_COM_ID) REFERENCES CLIENT_COMPLAINTS(ID) ON DELETE CASCADE;
ALTER TABLE CLIENT_COMPLAINTS DROP CONSTRAINT CLIENT_COMPLAINTS_ISSUE_FK;
ALTER TABLE CLIENT_COMPLAINTS ADD CONSTRAINT CLIENT_COMPLAINTS_ISSUE_FK FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE(ID) ON DELETE CASCADE;
delete from issue where urgency_id not in (select sys_id from client);
ALTER TABLE ISSUE ADD CONSTRAINT ISSUE_CLIENT_FK FOREIGN KEY (URGENCY_ID) REFERENCES CLIENT(SYS_ID) ON DELETE CASCADE;

delete from issue where issue_title = 'طلب تسليم' or issue_title = 'Extracting';
delete from ISSUE_DOCUMENT;
delete from ISSUE_DOCUMENT_DATA;