DELETE FROM RESERVATION;
DELETE FROM CLIENT_PROJECTS WHERE PRODUCT_ID = 'reserved';
DELETE FROM ISSUE_STATUS WHERE OBJECT_TYPE = 'RESERVATION';
UPDATE ISSUE_STATUS SET STATUS_NAME = '8' WHERE STATUS_NAME = '9';