SELECT * FROM 
(
    SELECT USERS.*, ROWNUM AS INDCIES 
        FROM USERS LEFT JOIN EMP_MGR EM ON USER_ID = EM.EMP_ID 
        WHERE LOWER(USER_NAME) LIKE LOWER('%%') AND EM.ID IS NULL 
) WHERE INDCIES BETWEEN ? AND ?

select * from PCRM2.EMP_MGR