CREATE TABLE STANDARED_PAYMENT_PLAN 
(	
    SPLAN_ID VARCHAR2(20 BYTE), 
    PLAN_TITEL VARCHAR2(20 BYTE), 
    PMT_AMT NUMBER(20,0), 
    DOWN_PMT_AMT NUMBER(20,0), 
    DOWN_PMT_DATE NUMBER(20,0), 
    FRIST_INSTALLMENT_DATE NUMBER, 
    INSTALLMENT_SYS NUMBER(20,0), 
    INSTALLMENT_NUM NUMBER(20,0), 
    RESERVATION_AMT NUMBER(20,0), 
    CREATED_BY VARCHAR2(20 BYTE), 
    CREATION_DATE DATE, 
    INSTALLMENT_AMT NUMBER
);
ALTER TABLE STANDARED_PAYMENT_PLAN MODIFY (SPLAN_ID NOT NULL);
ALTER TABLE STANDARED_PAYMENT_PLAN ADD CONSTRAINT STANDARED_PAYMENT_PLAN_PK PRIMARY KEY (SPLAN_ID) ENABLE;
CREATE TABLE STNDRD_PYMNT_PLN_TOLERANCE 
(	
    ID VARCHAR2(50 BYTE), 
    SPLAN_ID VARCHAR2(50 BYTE), 
    RESERVATION_AMT_MIN NUMBER, 
    RESERVATION_AMT_MAX NUMBER, 
    DOWN_PMT_AMT_MIN NUMBER, 
    DOWN_PMT_AMT_MAX NUMBER, 
    INSTALLMENT_NUM_MIN NUMBER, 
    INSTALLMENT_NUM_MAX NUMBER, 
    OPTION1 VARCHAR2(50 BYTE), 
    OPTION2 VARCHAR2(50 BYTE), 
    OPTION3 VARCHAR2(50 BYTE)
);
ALTER TABLE STNDRD_PYMNT_PLN_TOLERANCE MODIFY (ID NOT NULL);
ALTER TABLE STNDRD_PYMNT_PLN_TOLERANCE ADD CONSTRAINT STNDRD_PYMNT_PLN_TOLERANCE_PK PRIMARY KEY (ID) ENABLE;

ALTER TABLE PAYMENT_PLAN ADD CONSTRAINT u_t UNIQUE (PLAN_TITLE, CLIENT_ID, UNIT_ID);

//DELETE PAYMENT PLANS FOR ALL CLIENTS
DELETE FROM  PAYMENT_PLAN;
DELETE FROM  PAYMENT_PLAN_DETAILS;

//DELETE ALL PAYMENT PLANS
DELETE FROM  STANDARED_PAYMENT_PLAN;
DELETE FROM STNDRD_PYMNT_PLN_TOLERANCE;


