UPDATE CLIENT SET NAME = TRANSLATE(NAME, CHR(10) || CHR(13) || CHR(9), '  '), EMAIL = TRANSLATE(EMAIL, CHR(10) || CHR(13) || CHR(9), '  '), MOBILE = TRANSLATE(MOBILE, CHR(10) || CHR(13) || CHR(9), '  '), DESCRIPTION = TRANSLATE(DESCRIPTION, CHR(10) || CHR(13) || CHR(9), '  ') WHERE REGEXP_LIKE(TRIM(NAME), '[[:space:]]$') OR REGEXP_LIKE(TRIM(EMAIL), '[[:space:]]$') OR REGEXP_LIKE(TRIM(MOBILE), '[[:space:]]$') OR REGEXP_LIKE(TRIM(DESCRIPTION), '[[:space:]]$');


SELECT * FROM CLIENT_COMPLAINTS WHERE TRUNC(CURRENT_STATUS_SINCE) = '31-Oct-2018';