# Sample ResourceBundle properties file
# to do add french to this
delete=&#1581;&#1584;&#1601;
view=&#1605;&#1588;&#1575;&#1607;&#1583;&#1607;
viewdetails=&#1605;&#1588;&#1575;&#1607;&#1583;&#1577; &#1575;&#1604;&#1578;&#1601;&#1575;&#1589;&#1576;&#1604;
edit=&#1578;&#1581;&#1585;&#1610;&#1585;

tasks=Task(s)
supplierlist=Supplier List

grouplist= Group List
userlist=User List
projectlist=Site List
departmentlist=Department List
techlist=Technicians List
placelist=Places List
milestonelist=Milestone List
maintenancelist=Maintenance List
issuetypelist=Task Type List
urgencylist=Urgency Level List
doclist=Document List
accountlist=Account List
accountitemlist= Account Item List
businessclasslist= Business Classifications List
selectaccount=Select Account

areyousure=Are You Sure?
allfieldsrequired=All (*) Fields are required
cantdelete=Can't Delete
youcantdelete=You can't delete

selectworker=Select the Worker
workername=Worker Name
workernote=Worker Note

deleteproject=Delete Site
projectname=Site Name
eqNO=Site NO.
updateexistingproject=Update Existing Site
updateproject=Update Site
projectupdatestatus=Site Update Status
projectdesc=Site Description
viewproject=View Existing Site
addnewproject=Add New Site
projectsavingstatus=Site Saving Status
saveproject=Save Site
selectproject=Select Site And Status

deletedepartment=Delete Department
departmentname=Department Name
updateexistingdepartment=Update Existing Department
updatedepartment=Update Department
departmentupdatestatus=Department Update Status
departmentdesc=Department Description
viewdepartment=View Existing Department
addnewdepartment=Add New Department
departmentsavingstatus=Department Saving Status
savedepartment=Save Department
selectdepartment=Select Department And Status

addnewtech=Add New Technician
deletetech=Delete Technician
techname=Technician Name
updateexistingtech=Update Existing Technician
updatetech=Update Technician
techupdatestatus=Technician Update Status
techjob=Technician Job Title
viewtech=View Existing Technician
techsavingstatus=Technician Saving Status
savetech=Save Technician
selecttech=Select Technician And Status

addnewcat=Add New Equipment Category
addnewbasecat=Add New Equipment Base Category
deletecat=Delete Category
catname=Name
updateexistingcat=Update Existing Category
updatecat=Update Category
updatebasecat=Update Base Category
catupdatestatus=Category Update Status
catjob=Category Job Title
viewcat=View Existing Category
catsavingstatus=Category Saving Status
savecat=Save Category
parentcategory=Parent Category
catdescription=Description
catlist=Equipment Category List

addnewequipment=Add New Equipment
deleteequipment=Delete Equipment
equipmentname=Equipment Name
updateexistingequipment=Update Existing Equipment
updateequipment=Update Equipment
equipmentupdatestatus=Equipment Update Status
viewequipment=View Existing Equipment
equipmentsavingstatus=Equipment Saving Status
saveequipment=Save Equipment
parentequipment=Parent Equipment
equipmentdescription=Equipment Description
purchasedate=Purchase Date
operationstartdate=Operation Start Date
noofworkinghours=Number of Working Hours
equipmentlist=Equipment List

deleteplace=Delete Place
placename=Place Name
updateexistingplace=Update Existing Place
updateplace=Update Place
placeupdatestatus=Place Update Status
placedesc=Place Description
viewplace=View Existing Place
addnewplace=Add New Place
placesavingstatus=Place Saving Status
saveplace=Save Place
selectplace=Select Place And Status

deletemilestone=Delete Milestone
milestonename=Milestone Name
updateexistingmilestone=Update Existing Milestone
updatemilestone=Update Milestone
milestoneupdatestatus=Milestone Update Status
milestonedesc=Milestone Description
viewmilestone=View Existing Milestone
addnewmilestone=Add New Milestone
milestonesavingstatus=Milestone Saving Status
savemilestone=Save Milestone

deleteissuetype=Delete Task Type
issuetypename=Task Type Name
updateexistingissuetype=Update Existing Task Type
updateissuetype=Update Task Type
issuetypeupdatestatus=Task Type Update Status
issuetypedesc=Task Type Description
viewissuetype=View Existing Task Type
addnewissuetype=Add New Task Type
saveissuetype=Save Task Type
issuetypesavingstatus=Task Type saving Status

viewissuedetail=View Task Detail
issuetitle=Task Title
issuetype=Task Type
issuedesc=Task Description
rejectissue=Reject Task

deleteurgency=Delete Urgency Level
urgencyname=Urgency Name
updateexistingurgency=Update Existing Urgency Level
updateurgency=Update Urgency Level
urgencyupdatestatus=Urgency Level Update Status
urgencydesc=Urgency Description
viewurgency=View Existing Urgency Level
addnewurgency=Add New Urgency Level
saveurgency=Save Urgency
urgencysavingstatus=Urgency Saving Status
urgencytype=Urgency Type

deletemaintenance=Delete Maintenance
maintenancename=Maintenance Name
updateexistingmaintenance=Update Existing Maintenance
updatemaintenance=Update Maintenance
maintenanceupdatestatus=Maintenance Update Status
maintenancedesc=Maintenance Description
viewmaintenance=View Existing Maintenance
addnewmaintenance=Add New Maintenance
savemaintenance=Save Maintenance
maintenancesavingstatus=Maintenance Saving Status
maintenance=Maintenance

expectedenddate=Expected End Date

isrisk=Risk

cancel=&#1573;&#1606;&#1607;&#1575;&#1569;
search=Search
status=Status

searchtitle=Title Search With

begindate=Begin Date
enddate=End Date

confirmselection=Confirm Selection

foraccount=For Account

searchtitle=Search Title For

searchdocument=Search Documents For

keyword=Keyword

executesearch=Execute Search

bookmark=Bookmark Document

backtolist=&#1575;&#1604;&#1593;&#1608;&#1583;&#1607; &#1594;&#1604;&#1609; &#1575;&#1604;&#1602;&#1575;&#1574;&#1605;&#1577;


savebookmark=Save Bookmark

doctitle=Document Title

bookmarktext=Bookmark Text

documentimage=Document Image

contact=Please Contact System Administrator
#View Document Details 
viewdocumentdetails=View Document Details

systemid=System Identfication

accountname=Account Name

accountclass=Account Classification

docdate=Document Date

facevalue=Face Value

createdby=Created By

creationtime=Creation Time

creationdate=Creation Date

currentstatus=Current Status

assignedby=Assigned By

assignedto=Assigned To

expectedbdate=Expected Begin Date

expectededate=Expected End Date

finishedtime=Finished Time

#Description de document
documentdescription=Document Description

viewbookmark=View Bookmark

scheduleList = Task List

Configure = Configure

addNewItem = Add New Equipment Item
saveItem = Save Item
saveItemStatus = Item Saving Status
EquipmentName = Equipment Name
category = Category
itemCode = Item Code
itemUnit = Unit
itemPrice = Price

scheduleConfig = Task Configuration
saveSchedule = Save Configuration
addSchedule = Create new Task
saveSchedule = Save Task
scheduleTitle = Task Title
frequency = Frequency
frequencyType = Frequency Type
scheduleSavingStatus=Task Saving Status
scheduleUnits = Activate Task
listScheduleUnits = List Task Units
unitSchedules = Unit Tasks List
scheduleDuration = Task Duration
monthMsg = You must select a month
month=Month
year = Year
jan=Jan
feb=Feb
mar=Mar
apr=Apr
may=May
jun=Jun
jul=Jul
aug=Aug
sep=Sep
oct=Oct
nov=Nov
dec=Dec

day=Day

