# Sample ResourceBundle properties file

attachbefore=Attach file before filling in form
doccreationstatus=Document Creation Status
selectimagefile=Select Image File
selectpdffile=Select PDF File
selectwordfile=Select Word File
selectexcelfile=Select Excel File
selectemlfile=Select Outlook File
selecthtmlfile=Select Html File
doctitle=Document Title
accntclass=Account Classification
year=Year
month=Month
day=Day
docdesc=Document Description
facevalue=Face Value [If Money]
docdate=Document Date
noclass=* No classifications are attached to this account. Go to "Bussiness Admin" menu to associate classifications.
cancel=Cancel
createnewdoc=Create New Document
selectclient=Select Client
attachment=attachement
savedoc=Save Document
attachimage=Attach Image
attachpdf=Attach PDF File
attachhtml=Attach HTML File
attacheml=Attach EML file
attachword=Attach Word File
createnewimagedoc=Create New Image Document
createnewpdfdoc=Create New PDF Document
createnewworddoc=Create New Word Document
createnewexceldoc=Create New Excel Document
createnewhtmldoc=Create New Html Document
createnewoutlookdoc=Create New Outlook Document
