# Sample ResourceBundle properties file
# {"Title","Account","Account Item","Date","View Document","More Details","Delete","Bookmark"};

0=Title
1=Account
2=Account Item
3=Date
4=Face Value
5=View Document
6=More Details
7=Delete
8=Bookmark

