# Sample ResourceBundle properties file

0=Créer un document d'images
1=Créer un document PDF
2=Créer un document HTML[Text seulement]
3=Créer un document MS Word
4=Créer un document MS Excel
5=Créer un document MS OutLook
6=Lister les documents par compte
7=Lister tous les documents
8=Recherche par titre
9=Rechercher dans les documents
10=Rechercher mes titres
11=Rechercher mes documents
12=Lister mes documents
13=Nouveau groupe
14=Nouveau usager
15=Liste d'uagers
16=Liste des groupes
17=Nouveau compte
18=Nouvelle classification
19=Nouvelle classification de compte
20=Lister les comptes
21=Lister les classifications
22=Lister les comptes
23=\u00C0 propos
24=Pr\u00E9sentation audio

