# Sample ResourceBundle properties file

intro=This Document Management System [DMS] enables businesses to store classified  document images, Word, Excel, MS OutLook, PDF and HTML files in database Subsequently documents can be retrieved for review, print or e-mail.

0=Integrated with Microsoft Word popular word processor

1=Integrated with Microsoft OutLook Mail Client

2=Integrated with Microsoft Excel popular spread sheet

3=Use as easy as surfing the net [Browser Interface]

4=Centralized Database accessible from all company departments

5=Globally accessible

6=Remote Business Management

7=Offline document vieweing [On Business Trip for example]

8=Runs on Regular PC's [Small Business]

9=Runs within office only or on internet [customer choice]

10=Document bookmarking

title=About This Software

done=OK

intro0=This

intro1=Document Management System

intro2=[DMS]

intro3=enables businesses to store classified

intro4=document images, Word, Excel, MS OutLook, PDF and HTML files

intro5=in database

intro6=Subsequently documents can be retrieved for review, print or e-mail.
