insert into project_acc (PROJECT_ACC_ID, MAX_INSTALMENT, PROJECT_ID, OPTION_1, OPTION_2, OPTION_3, CRETAION_TIME, CREATED_BY, METER_PRICE, GARAGE_NUM, LOCKER_NUM) 
select TEMP_SEQ.nextval, '0', prjID, null, null, null, SYSDATE, '1', NULL, NULL, NULL
from (select UNIQUE PROJECT_ID prjID from PROJECT WHERE LOCATION_TYPE = '44');