/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  walid
 * Created: Jun 21, 2018
 */



insert into client (SYS_ID, CLIENT_NO, NAME, GENDER, MATIRAL_STATUS, MOBILE, PHONE, SALARY, ADDRESS, EMAIL, ISACTIVE, CREATED_BY,
CLIENTNOBYDATE, CLIENTSSN, CREATION_TIME, AGE_GROUP, PARTNER, JOB, OPTION1, OPTION2, OPTION3, CODE, NATIONALITY, REGION, BIRTH_DATE,
CURRENT_STATUS, CURRENT_STATUS_SINCE, DESCRIPTION, BRANCH, INTER_PHONE) 
select TEMP_SEQ.nextval, TEMP_SEQ.nextval, nm, gndr, mtrs, mb, ph, sl, adr, em, ia, cb,
cnbd, csn, ct, ag, pr, jb, o1, o2, o3, cd, nt, rgn, bd,
cs, css, dsc, brn, intPh
from (select UNIQUE NAME nm , 'UL' gndr, 'UL' mtrs, MOBILE mb, 'UL' ph, 1000 sl, 'UL' adr, 'UL' em, 1 ia, 1 cb, '21-FEB-1978' cnbd, 
'UL' csn, sysdate ct, '30-40' ag, 'UL' pr, 'UL' jb, 0 o1, 0 o2, 'on' o3, 'UL' cd, 'UL' nt, 'UL' rgn, sysdate bd, 11 cs, sysdate css, 'UL' dsc,'UL' brn, 'UL' intPh
from MAALEM_CUSTOMERS);

insert into issue_status select TEMP_SEQ.nextval, '11', 'UL', 'UL', NULL, SYSDATE, 0, 'UL', 'UL', 'UL', sys_id, 'client', 'o', '1' from client where sys_id not in (select BUSINESS_OBJ_ID from issue_status where OBJECT_TYPE = 'client');

Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1529747146712','111B بيت الوطن','111B',to_date('23-JUN-18','DD-MON-RR'),'1','111B بيت الوطن','1364111290870','44','1','UL','UL','2','0-1364111290870','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1529747192415','26 E  بيت الوطن','26E',to_date('23-JUN-18','DD-MON-RR'),'1','26 E  بيت الوطن','1364111290870','44','1','UL','UL','2','0-1364111290870','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1529747216112','148 الاندلس','148',to_date('23-JUN-18','DD-MON-RR'),'1','148 الاندلس','1364111290870','44','1','UL','UL','2','0-1364111290870','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1529747238886','100الاندلس','100',to_date('23-JUN-18','DD-MON-RR'),'1','100الاندلس','1364111290870','44','1','UL','UL','2','0-1364111290870','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1529747260534','6E بيت الوطن','6E',to_date('23-JUN-18','DD-MON-RR'),'1','6E بيت الوطن','1364111290870','44','1','UL','UL','2','0-1364111290870','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1529747280726','136 الاندلس','136',to_date('23-JUN-18','DD-MON-RR'),'1','136 الاندلس','1364111290870','44','1','UL','UL','2','0-1364111290870','0','0',null,null,'1');

insert into PROJECT (PROJECT_ID, PROJECT_NAME, EQ_NO, CREATION_TIME, CREATED_BY, PROJECT_DESCRIPTION, MAIN_PROJ_ID, LOCATION_TYPE, FUTILE, COORDINATE, OPTION_ONE, OPTION_TWO, OPTION_THREE, IS_TRNSPRT_STN, IS_MNGMNT_STN, PROJECTFLAG) 
select TEMP_SEQ.nextval, PROJECT || ' ' || UNIT, 'UL', SYSDATE, 1, 'UL', PROJECT_ID, 'RES-UNIT', 1, 'UL', 'UL', 'UL', 'UL', 1, 1, 0 from MAALEM_CUSTOMERS where unit is not null;

insert into issue_status select TEMP_SEQ.nextval, '8', 'UL', 'UL', NULL, SYSDATE, 0, 'UL', 'UL', 'UL', project_id, 'Housing_Units', 'o', '1' from project where LOCATION_TYPE ='RES-UNIT';

update project set INTEGRATED_ID = '1529567399619' where LOCATION_TYPE = 'RES-UNIT';

Insert into CLIENT_PROJECTS select TEMP_SEQ.nextval || '11',c.sys_id,p.project_id,'1458260036819',sysdate,'purche','29','0','UL','UL','UL',P.PROJECT_NAME,nc.project,null,null,null,null,null,null from MAALEM_CUSTOMERS nc left join client c on C.NAME = NC.NAME left join project p on P.PROJECT_NAME = NC.PROJECT || ' ' || NC.UNIT where NC.UNIT is not null;

update issue_status set STATUS_NAME = '10' where BUSINESS_OBJ_ID in (select P.PROJECT_ID from MAALEM_CUSTOMERS nc left join client c on C.NAME = NC.NAME left join project p on P.PROJECT_NAME = NC.PROJECT || ' ' || NC.UNIT where NC.UNIT is not null);

1403765222538 CS team leader
1363767379185 خدمه العملاء

1420707686251 Call Ceter

tag CS in web.xml customerServiceID

Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1468836156942','شكوي من التشطيب','CML',to_date('18-JUL-16','DD-MON-RR'),'1','شكوي من التشطيب','1468838377022','cmplnt','0','UL','UL','UL','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1468838377022','التشطيبات - شكاوي','CML1',to_date('18-JUL-16','DD-MON-RR'),'1','التشطيبات - شكاوي','1363767608148','cmplnt','1','UL','UL','UL','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405151985257','الشكاوي','4535',to_date('12-JUL-14','DD-MON-RR'),'1','ert','0','cmplnt','1','UL','UL','1','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405152787059','تأخر استلام الوحدات ','C1',to_date('12-JUL-14','DD-MON-RR'),'1','تأخر استلام الوحدات ','1405151985257','cmplnt','0','UL','UL','2','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405152805790','لا يوجد كهرباء ','C2',to_date('12-JUL-14','DD-MON-RR'),'1','لا يوجد كهرباء ','1405151985257','cmplnt','0','UL','UL','2','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405152946875','عدم استكمال اعمال التشطيب ','C3',to_date('12-JUL-14','DD-MON-RR'),'1','عدم استكمال اعمال التشطيب ','1405151985257','cmplnt','0','UL','UL','2','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1420716968550','اخرى','oth',to_date('08-JAN-15','DD-MON-RR'),'1','غير مصنفه','1405151985257','cmplnt','1','UL','UL','2','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1489838926413','لا يوجد متابعة','45',to_date('18-MAR-17','DD-MON-RR'),'1','يسبيس','1405151985257','cmplnt','1','UL','UL','2','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1489843027223','لا يوجد ماء','fgff',to_date('18-MAR-17','DD-MON-RR'),'1','erw','1405151985257','cmplnt','1','UL','UL','2','1405151985257','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1489843850328','لا يوجد ماء - الماسورة مكسورة','45A',to_date('18-MAR-17','DD-MON-RR'),'1','dfgdf','1489843027223','cmplnt','1','UL','UL','3','1405151985257-1489843027223','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1489843904670','لم يتم بناء الحائط','fgf',to_date('18-MAR-17','DD-MON-RR'),'1','يبلي','1408522847821','cmplnt','1','UL','UL','3','UL-1408522847821','0','0',null,null,'1');
commit;



Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405155547227','إستعلامات','IN1',to_date('12-JUL-14','DD-MON-RR'),'1','sdsd','0','nqry','1','UL','UL','UL','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405155631963','اسعار وحدات','N2',to_date('12-JUL-14','DD-MON-RR'),'1','اسعار وحدات','1405155547227','nqry','0','UL','UL','UL','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405155756650','وحدات متاحة','N1',to_date('12-JUL-14','DD-MON-RR'),'1','وحدات متاحة','1405155547227','nqry','0','UL','UL','UL','UL','0','0',null,null,'1');
Insert into PROJECT (PROJECT_ID,PROJECT_NAME,EQ_NO,CREATION_TIME,CREATED_BY,PROJECT_DESCRIPTION,MAIN_PROJ_ID,LOCATION_TYPE,FUTILE,COORDINATE,OPTION_ONE,OPTION_TWO,OPTION_THREE,IS_TRNSPRT_STN,IS_MNGMNT_STN,INTEGRATED_ID,NEW_CODE,PROJECTFLAG) values ('1405155777542','منتجعات','N3',to_date('12-JUL-14','DD-MON-RR'),'1','منتجعات','1405155547227','nqry','0','UL','UL','UL','UL','0','0',null,null,'1');
commit;