# To change this template, choose Tools | Templates
# and open the template in the editor.
updateCurrentReading=select au.current_reading ,mu.unit_name,au.ACUAL_READING from average_unit au , maintainable_unit mu where au.unit_id=? and mu.id=au.unit_id