insert=insert into BUSINESS_EVENT values(?,?,?,?,?,SYSDATE,?,?,?)
updateReceipId=update DISTRIBUTION_LIST set receip_id=? where sys_id=?
updateOwnerId=update CLIENT_COMPLAINTS set current_owner_id=?,current_owner=? where id=?