insertCallingPlan=INSERT INTO CALLING_PLAN VALUES (?,?,?,?,?,?,SYSDATE,?,?,CALLING_PLAN_NUMBER.nextval,?)
insertCallingPlanStatus=INSERT INTO ISSUE_STATUS VALUES (?, ?, ?, ?, NULL, ?, '0', ?, ?, ?, ?, ?, ?, ?)
updateCallingPlanStatus=UPDATE CALLING_PLAN SET SCHEDULE_STATUS = ? WHERE ID = ?
getClientCampaigns=SELECT CP.* FROM CALLING_PLAN_DETAILS CPD LEFT JOIN CALLING_PLAN CP ON CPD.CALLING_PLAN_ID = CP.ID WHERE CPD.CLIENT_ID = ?