getClinetComplaintsToClosed=SELECT ID, ISSUE_ID FROM CLIENT_COMPLAINTS_TIME_LINE WHERE LAST_TIME_UPDATED_SECONDS >= ?
getClinetComplaintsToClosedByDepartmentCode=SELECT ID, ISSUE_ID FROM CLIENT_COMPLAINTS_TIME_LINE WHERE DEPARTMENT_CODE = ? AND LAST_TIME_UPDATED_SECONDS >= ?
getClinetComplaintsTimeLineFromFinish=SELECT * FROM CLIENT_COMPLAINTS_TIME_LINE