saveClientIncentives=INSERT INTO CLIENT_INCENTIVE VALUES (?,?,?,?,?,SYSDATE)
getIncentivesByClient=SELECT c.id, c.INCENTIVE_TITLE, cc.INCENTIVE_DATE FROM CLIENT_INCENTIVE cc right join INCENTIVE c on cc.INCENTIVE_ID = c.ID where cc.CLIENT_ID = ?
deleteOldClientIncentives=delete from CLIENT_INCENTIVE where CLIENT_ID = ?