insertClientSeasons= insert into CLIENT_SEASONS values(?,?,?,?,SYSDATE,?,?)
updateSeason=update CLIENT_SEASONS set notes=?,created_by=?,CREATION_TIME=SYSDATE where id=?
deleteSeason=delete from CLIENT_SEASONS where id =?