#insertClient= INSERT INTO client values(?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?)

insertClient= INSERT INTO client values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?,?,?,?,?)
updateClient=UPDATE client SET CLIENT_NO = ?, NAME = ?, GENDER = ?, MATIRAL_STATUS = ?, MOBILE = ?,PHONE=?, SALARY = ?, ADDRESS = ?, EMAIL = ?, CLIENTSSN = ?,AGE_GROUP=? ,partner=? ,ISACTIVE = ? ,option1=?,option2=?,job=? WHERE SYS_ID = ?
selectAllClientsName = select ID,Name from client t where id != 1
selectClient = select c.id,c.name from client c , eqp_client eq where eq.unit_id=? and eq.client_id=c.id
insertInitialClientStatus=INSERT INTO client_status(status_id, status_name, client_id, status_note, begin_date, end_date) VALUES(?, ?, ?, ?, SYSDATE, NULL)
getClientByCall=select * from client,issue where SYS_ID=URGENCY_ID and BUSINESS_ID=?
getClientByName=select * from CLIENT where NAME LIKE '%clientName%'
updateCounter=update client set option3=? where sys_id=1
getCounter=select option3 from client where sys_id=1

selectAllDataForClient=select * from client_view where client_id = ?

getMaxCodeOfClient=select max(to_number(code)) code from store_allcodes where groupf_id=23
checkCodeUnique=select * from store_allcodes where (to_number(code))=(to_number(?))
saveClientInRealEstate=insert into store_allcodes (code,ANAME,ENAME,STORE_ALLCODES_ID,GROUPF_ID,CASH_BEGIN_DEBIT,CASH_BEGIN_CREDIT,CHECK_BEGIN_DEBIT,CHECK_BEGIN_CREDIT) values (?,?,?,STORE_ALLCODES_SEQ.nextval,23,0,0,0,0)
getClientInRealEstate=select STORE_ALLCODES_ID as clientId from store_allcodes where code=? and groupf_id=23
updateClientInRealEstate=update store_allcodes set ANAME=? ,ENAME=? where  STORE_ALLCODES_ID=?
deleteClientInRealEstate=delete from store_allcodes where STORE_ALLCODES_ID=?

getClientReportByDate=select * from CLIENT t where t.creation_time >=?;
getClientReportByAgeGroup=select * from CLIENT  where AGE_GROUP = ?
getClientReportByjob=select * from CLIENT  where job = ?
clients=select * from client

