insertComplaintEmployee=INSERT INTO complaint_employee (ID, COMPLAINT_ID, EMPLOYEE_ID, NOTES, CREATION_TIME, CREATED_BY, RESPONSIBLITY) VALUES (?,?,?,?,SYSDATE,?,?)
selectAllResponsibles=select * from complaint_employee where responsiblity is not null
updateComplaintEmployee=update complaint_employee set mail_group_id=? where employee_id=?