insertData = insert into customer_grades values (?,?,?,?,null)
getAllEqp = select equep_id from emp_cars where type=?
getAllDrivers=select Employee.Emp_Name,maintainable_unit.unit_name,emp_cars.start_date \
              from emp_cars Inner join Employee on employee.emp_id=emp_cars.empid \
             inner join maintainable_unit on maintainable_unit.id=emp_cars.equep_id \
             where emp_cars.type=? and emp_cars.start_date between ? and ?
getDriverAndSupervisorName=select emp.emp_name, ec.type from emp_cars ec inner join employee emp on ec.empid=emp.emp_id \
                           where ec.equep_id = ?
getAttachedEmployees=SELECT DISTINCT empid FROM emp_cars
getGrades=SELECT * FROM grades
upsertEqpEmp=MERGE INTO customer_grades USING dual ON (id = ?) WHEN MATCHED THEN UPDATE SET customer_id = ?, start_date = ? WHEN NOT MATCHED THEN INSERT (id, customer_id, grade_id, start_date, end_date) VALUES (?,?,?,?,null)
updateEndDate=UPDATE customer_grades t SET end_date = ? WHERE t.customer_id = ? AND t.end_date IS NULL
updateStartDate=UPDATE customer_grades t SET start_date = ? WHERE t.grade_id = ? AND t.customer_id = ?
getEmployeeNameByType=SELECT e.emp_name employeeName FROM employee e, emp_cars ec WHERE e.emp_id = ec.empid AND ec.equep_id = ? AND ec.type = ? AND ec.end_date IS NULL