insert=INSERT INTO CUSTOMIZATION_PANEL VALUES(?, ?, ?, ?, ?, SYSDATE)
deleteByUser=DELETE FROM CUSTOMIZATION_PANEL WHERE USER_ID = ?
getByUserId=SELECT * FROM CUSTOMIZATION_PANEL WHERE USER_ID = ?
getByUserIdAndName=SELECT * FROM CUSTOMIZATION_PANEL WHERE USER_ID = ? AND NAME = ?