# To change this template, choose Tools | Templates
# and open the template in the editor.

Get_Equip_Details=select ID,AVERAGE,CURRENT_READING,UNIT_NAME,ENTRY_TIME  FROM EQUIP_BY_AUTO_UPDATE_READING  WHERE PARENT_ID=?
Get_Date = select distinct(ES.END_DATE- ES.BEGIN_DATE ) GET_DIFFRENECE from EQUIP_STATUS ES ,EQUIP_BY_AUTO_UPDATE_READING EP where EQUIPMENT_ID = ? AND STATE_ID =2 AND ES.BEGIN_DATE between EP.ENTRY_TIME AND sysDate