getDefaultGroup=SELECT GROUP_ID, GROUP_NAME, DEFAULT_PAGE FROM USER_GROUP WHERE USER_ID = ? AND IS_DEFAULT = '1'
cloneGroup=INSERT INTO TRACKER_GROUP SELECT ?, ?, ?, ?, SYSDATE, DEFAULT_PAGE, GROUP_MENU FROM TRACKER_GROUP WHERE GROUP_ID = ?
getAllGroups=SELECT GROUP_ID,GROUP_NAME FROM TRACKER_GROUP