insertJspType= INSERT INTO JSP_TYPES values(?,?,?,?,?,?,SYSDATE)
updateJspType=UPDATE Jsp_Types SET CLIENT_NO = ?, NAME = ?, DESIGNATION = ?, ADDRESS = ?, CITY = ?, PHONE = ?, FAX = ?, EMAIL = ?, SERVICE = ?, IS_ACTIVE = ?, NOTE = ? WHERE ID = ?
selectAllJspTypesName = select ID,Name from client t where id != 1
selectJspType = select c.id,c.name from client c , eqp_client eq where eq.unit_id=? and eq.client_id=c.id



