insert = INSERT INTO LOCATION_TYPES VALUES (?,?,?,?,?,?)
update = update LOCATION_TYPES set type_code = ?, ar_desc = ?, en_desc = ? where id = ?
delete = delete from LOCATION_TYPES where id = ?
updateDisplayInTree=UPDATE LOCATION_TYPES SET COL_TWO = ? WHERE ID inValue (ids)
getLocationTypesMap=SELECT * FROM TICKET_TYPE WHERE TYPE_ID IN (inStatement)
getLocationTypeUsingLike = SELECT * FROM LOCATION_TYPES WHERE TYPE_CODE LIKE ?