insert=INSERT INTO LOGIN_INFORMATION VALUES(?, SYSDATE)
update=UPDATE LOGIN_INFORMATION SET LAST_LOGIN = SYSDATE WHERE USER_ID = ?
delete=DELETE FROM LOGIN_INFORMATION WHERE USER_ID = ?
select=SELECT LAST_LOGIN FROM LOGIN_INFORMATION WHERE USER_ID = ?