getEquipBySites=select * from maintainable_unit where IS_MAINTAINABLE='1' and IS_DELETED ='0' and SITE IN (sss)
getEquipBySubNameAndSites=select * from maintainable_unit where IS_MAINTAINABLE='1' and IS_DELETED ='0' and UNIT_NAME LIKE '%ppp%' AND SITE IN (sss)
getEquipBySubCodeAndSites=select * from maintainable_unit where IS_MAINTAINABLE='1' and IS_DELETED ='0' and UNIT_NO LIKE '%ppp%' AND SITE IN (sss)
