# To change this template, choose Tools | Templates
# and open the template in the editor.

saveSiteRelation        =INSERT INTO ORGN_DSTN_RLN Values(?,?,?,?,?,?,?,SYSDATE, ?, ?)
addProjectsRelation     =INSERT INTO ORGN_DSTN_RLN Values(?,?,?,?,?,?,?,SYSDATE, SYSDATE, SYSDATE)
getTwoProjectsRelation  = select * from ORGN_DSTN_RLN where PROJ_ONE = ? and PROJ_TWO = ?
updateProjectsDist      = update ORGN_DSTN_RLN set distance = ? where ID = ?
updateProjectsCost      = update ORGN_DSTN_RLN set dist_cost = ? where ID = ?
updateDelProjectsAccess = update ORGN_DSTN_RLN set accessible = ?, dist_cost = '0' , distance = '0' where ID = ?
updateProjectsAccess    = update ORGN_DSTN_RLN set accessible = ? where ID = ?
getDistinctProjectsTwo  = select distinct(proj_two)from ORGN_DSTN_RLN order by proj_two
getAllProjectsRelations = select * from ORGN_DSTN_RLN order by proj_two
updateProjRelations     = update ORGN_DSTN_RLN set dist_cost = ? , distance = ?, accessible = ?, valid_from = ?, valid_to = ? where ID = ?