insert= insert into OUT_OF_STORE_PARTS values(?,?,?,?,?,?,?,?,?,?,SYSDATE,?)

getItemsByManufacturingNo= select * from OUT_OF_STORE_PARTS where MANUFACTORY_NO = ? 

insertPartsModel=insert into parts_model values(?,?,sysdate)

update=update OUT_OF_STORE_PARTS set NAME_AR=?,NAME_EN=?,PAGE_NO=?,ITEM_NO=?,MANUFACTORY_NO=?,EXPECTED_PRICE=?,COMMENTS=?,ITEM_TYPE=? where id=?
