# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

insertSession=INSERT INTO PERSISTENT_SESSION VALUES(?,?,SYSDATE,?,?,?,'UL')
updateSession=UPDATE PERSISTENT_SESSION set user_id=?,loggin_in_time=SYSDATE,user_name=?, manager_id = ?, OPTION_1 = ? where computer_ip=?
getLoggedUsers=SELECT USER_ID FROM PERSISTENT_SESSION WHERE TRUNC(LOGGIN_IN_TIME) = TRUNC(SYSDATE)
getUsersWithDepartment=SELECT PS.*, CASE WHEN P.PROJECT_NAME IS NOT NULL THEN P.PROJECT_NAME WHEN MP.PROJECT_NAME IS NOT NULL THEN MP.PROJECT_NAME || ' (Manager)' ELSE NULL END DEPARTMENT_NAME FROM PERSISTENT_SESSION PS LEFT JOIN EMP_MGR EM ON PS.USER_ID = EM.EMP_ID LEFT JOIN PROJECT P ON EM.MGR_ID = P.OPTION_ONE LEFT JOIN PROJECT MP ON MP.OPTION_ONE = PS.USER_ID
