addEntity = INSERT INTO PROJECT_ENTITIES VALUES(?, ?, ?, ?, ?, ?, ?)
getEntity = SELECT ENTITY_ID, ENTITY_TYPE, ENTITY_PRICE, ENTITY_AREA FROM PROJECT_ENTITIES WHERE PROJECT_ACC_ID = ?
updateEntity = UPDATE PROJECT_ENTITIES SET updateAtt WHERE ENTITY_ID = ?
daleteEntity = DELETE PROJECT_ENTITIES WHERE ENTITY_ID = ?
getEntityByType = SELECT ENTITY_ID, ENTITY_TYPE, ENTITY_PRICE, ENTITY_AREA FROM PROJECT_ENTITIES WHERE PROJECT_ACC_ID = ? AND ENTITY_TYPE = ?