insertQualityPlan=INSERT INTO QUALITY_PLAN VALUES (?,?,?,?,?,?,?,SYSDATE,?,?,QUALITY_PLAN_NUMBER.nextval,?,?)
insertQualityPlanStatus=INSERT INTO ISSUE_STATUS VALUES (?, ?, ?, ?, NULL, ?, '0', ?, ?, ?, ?, ?, ?, ?)
updateQualityPlanStatus=UPDATE QUALITY_PLAN SET SCHEDULE_STATUS = ? WHERE ID = ?