insert=INSERT INTO QUARTZ_FINISH_SCHEDULER VALUES(?,?,?,?,?,SYSDATE,?,?,?)
updateInterval=UPDATE QUARTZ_FINISH_SCHEDULER SET INTERVAL = ? WHERE ID = ?
updateRunning=UPDATE QUARTZ_FINISH_SCHEDULER SET RUNNING = ? WHERE ID = ?
delete=DELETE FROM QUARTZ_FINISH_SCHEDULER WHERE ID = ?
getAllDepartments=SELECT Q.*, P.PROJECT_ID AS DEPARTMENT_ID, P.PROJECT_NAME AS DEPARTMENT_NAME FROM QUARTZ_FINISH_SCHEDULER Q RIGHT OUTER JOIN PROJECT P ON P.PROJECT_ID = Q.OBJECT_ID WHERE LOCATION_TYPE = 'div'
