insert=INSERT INTO QUARTZ_SCHEDULER VALUES(?,?,?,?,?,?,?,?,SYSDATE,?,?,?)
updateInterval=UPDATE QUARTZ_SCHEDULER SET INTERVAL = ? WHERE ID = ?
updateRunning=UPDATE QUARTZ_SCHEDULER SET RUNNING = ? WHERE ID = ?
delete=DELETE FROM QUARTZ_SCHEDULER WHERE ID = ?
getByObjectTypeAndAction=SELECT * FROM QUARTZ_SCHEDULER WHERE OBJECT_TYPE = ? AND ACTION = ?
getAllDepartments=SELECT Q.*, P.PROJECT_ID AS DEPARTMENT_ID, P.PROJECT_NAME AS DEPARTMENT_NAME FROM QUARTZ_SCHEDULER Q RIGHT OUTER JOIN PROJECT P ON P.PROJECT_ID = Q.OBJECT_ID WHERE LOCATION_TYPE = 'div'
