recordSeason=INSERT INTO record_season values(?,?,?,?,?,?,?,?,SYSDATE,?,?,?,?,?)
updateRecordSeason=update record_season set ENGLISH_NAME=? ,ARABIC_NAME=?,COST=?, IS_FOREVER=? ,S_TYPECODE=? where id=?
getToolsForCampaign=select * from RECORD_SEASON where ID in (select tool_id from CAMPAIGN where parent_id = ?)
recordSeasonCampaign=Insert into CAMPAIGN values (TEMP_SEQ.nextval,?,'UL',sysdate,sysdate,0,'100','0','compound','16',sysdate,'1520338554973',sysdate,3)


