selectAll = select * from SCHEDULES_TASKS_RLN_MODEL
selectAllByModelId = select * from SCHEDULES_TASKS_RLN_MODEL where UNIT_NO = ?
selectAllByModelAndTask = select * from SCHEDULES_TASKS_RLN_MODEL where UNIT_NO = ? and task_id = ?
selectScheduleCountByModelId = select Count(DISTINCT scheduleID) AS countSchedule from SCHEDULES_TASKS_RLN_MODEL  where UNIT_NO = ?