insertSeasonPlan=INSERT INTO season_plan (ID, SEASON_ID, PLAN_ID, NOTES, CREATED_BY, CREATION_TIME) VALUES (?,?,?,?,?,SYSDATE)
getAttachedSeasons=select DISTINCT(season_id) from season_plan WHERE plan_id = ?
getAttachedPlans=SELECT p.* FROM season_plan sp, plan p WHERE p.plan_id = sp.plan_id AND sp.season_id = ?