insertUserArea= INSERT INTO SERVICEMAN_AREA values(?,?,?,?,?,SYSDATE,?,?,?,?,?)
getUserArea=select * from SERVICEMAN_AREA where user_id=?
getSupervisorArea=select * from SERVICEMAN_AREA where SERVICE_IN=? and ROLL_ID=?
