getUnit=select * from UNIT_STATUS_VIEW where project_name LIKE '%text%' and main_proj_id=?
getUnitWithoutParent=select * from UNIT_STATUS_VIEW where project_name LIKE '%text%' and location_type='RES-UNIT' 


