saveUserArea=INSERT INTO USER_AREA VALUES (?,?,?,?,?,NULL,?,SYSDATE)
updateUserAreaEndDate=UPDATE USER_AREA SET END_DATE = ? WHERE USER_ID = ? AND END_DATE IS NULL
getLastUserArea=SELECT *FROM USER_AREA WHERE END_DATE IS NULL AND USER_ID = ?