insertData = insert into user_clients (id,user_id, client_id,comments, from_date,relation_type, end_date,trade_id) VALUES (?,?,?,null,?,?,null,?)
getAllEqp = select equep_id from emp_cars where type=?
getAllDrivers=select Employee.Emp_Name,maintainable_unit.unit_name,emp_cars.start_date \
              from emp_cars Inner join Employee on employee.emp_id=emp_cars.empid \
             inner join maintainable_unit on maintainable_unit.id=emp_cars.equep_id \
             where emp_cars.type=? and emp_cars.start_date between ? and ?
getDriverAndSupervisorName=select emp.emp_name, ec.type from emp_cars ec inner join employee emp on ec.empid=emp.emp_id \
                           where ec.equep_id = ?
getAttachedEmployees=SELECT DISTINCT user_id FROM user_clients
getUnitEmployees=SELECT e.full_name, ec.from_date, ec.relation_type FROM user_clients ec, users e WHERE ec.user_id = e.user_id AND ec.client_id = ? AND ec.end_date is null ORDER BY ec.relation_type ASC
upsertClientEmp=MERGE INTO user_clients USING dual ON (client_id = ? AND relation_type = ?) WHEN MATCHED THEN UPDATE SET user_id = ?, from_date = ? WHEN NOT MATCHED THEN INSERT (id,user_id, client_id,comments, from_date,relation_type, end_date) VALUES (?,?,?,null,?,?,null)
updateTypeEndDate=UPDATE user_clients t SET end_date = ? WHERE t.client_id = ? AND t.relation_type = ? AND t.end_date IS NULL
updateTypeStartDate=UPDATE user_clients t SET from_date = ? WHERE t.user_id = ? AND t.client_id = ?
getCompetentEmp=select * from user_clients where client_id=? and end_date is null
getEmployeeNameByType=SELECT e.emp_name employeeName FROM employee e, emp_cars ec WHERE e.emp_id = ec.empid AND ec.equep_id = ? AND ec.type = ? AND ec.end_date IS NULL