direction=ltr
noClient = Client No.
nameClient = Client Name
Notes = Notes
Search = Search
Message = No.Client / Phone / Mobile / Latest
Message2 = The client does not exist
Message3 = Enter content search
tableHeader[0] = Client No.
tableHeader[1] = Client Name
tableHeader[2] = Client Status
tableHeader[3] = Cell Phone
tableHeader[4] = Email
contentsearchln = Minimum Three Characters 
