direction=ltr
textalign=left
choose=Choose
save=Save
cancle=Cancle
saved=Saved Successfully
notsaved=Fail To Save
#new_building.jsp
newbuilding=New Building
floors=Floors No.
apartments=Apartments No.
 apartmentcode=Apartment Code
model=Model
cart=Add To Cart
mail=Send Details
apartmentexistsexist=Apartment already exists
appartmentno=Building No.
totalarea=Total Area
buildarea=Building Area
garages=Garages No
elevators=Elevator
garden=Garden
model1=Model
error1=Select 
error2=Select a Project
error3=Select a Model
error4=Enter the Appartment No.
error5=Enter the Floors No.
error6=Enter the Apartments No.
update=Update
linkunits=Unit-Model Association
noUnitSelectedMsg=No Unit Selected
selectModelMsg=Select a model
unit=Unit
ad=AD
view=View
project=project
CreationTime=Creation Time
CreatedBy=Created By
AdditionTime=Addition Time
unitmodel=Model
upload=Upload
filesuploaded=Done Upload
attach=Attach Engineering Drawing
showunitfiles=Show Unit Files
showmodelfiles=Show Model Files
showimages=Show All Images
filesnotuploaded=Upload Files Failed
listdocs=List Documents
newunit=New Unit
error7=Enter Unit Code
addnewunit=Add New Unit
showbuildingfiles=Show Building Files
showcompoundfiles=Show Compound Files
addmodel=Add Model
showlocs=Show Locations
addloc=Add Location on Map
modelname=Model Name
status=Status
showmaps=Show Project Pictures
modelerror=This Model name is already exist
showmap=Show Location on Map
showbulidings=Show Buildings
listunits=Units List
showattachments=Show Attachments
unitspricing=Units Pricing
unitArea=Area
indate=Date
meterprice=Meter Price
delete=Delete
building=Building
delbuild=Delete Building - Are you Sure ?
deleteddone=Deleted Successfully
deletednotdone=Failed to Delete
updateddone=Updated Successfully
updatenotdone=Failed to Update
price=Total Price
commstate=Commersial State
unitsno=Units No.
viewunitdetails=View Unit Details
unitdetails=Unit Details
modeldetails=Model Details
netarea=Net Area
rooms=Rooms
kitchens=Kitchens
pathrooms= BathRooms
scarification=Scarification Type
balcony=Balcony
nomodeldetails=No Details Available for this model
unitno=Unit No.
unitprice=Unit Price
unitarea=Unit Area
noimageunit=No Images For This Unit
noimagemodel=No Images For This Model
notfound=NotFound
payment=Payment Method
attachmodel=Attach  Model
clientdetails=Client Details
unitinstallment=Unit installment system
deposit=Deposit
depositperc=Deposit Perc.
calculate=Calculate
year=Year
installment=Installment
month=month
addunitmodel=Add residential  model
basicdata=Basic Data
details=Details
regdate=Registration Date
search=Search
fromdate=From Date
todate=To Date
availableunits=Available Units
contract=Rent Contract
viewresmodels=View residential models
resmodelsno=residential models No.
modelcode=Model Code
projectname=Project Name
fullName= Created By
totalphotos=Total Photos
attachphoto=Attach Photo
attachfile=attach file
vieweditresmodel=View/Edit residential models
desc=Description
classify=Classification
store=Store
club=Club
garage=Garage
theprice=Price
show=Show
all=All
phase=Phase
realestateUnits=Units from Real Estate
code=Code
linkUnit=Synchronize
cancel=Cancel
linkLabel=Synchronize
reUnitMessage=Select Unit (Real Estate)
linkMsg=Unit linked successfully
select=Select
unitStatus=Unit Type

addDate = Add Date
chsDate = Choose Date
dateType = Date Type
construction = Construction Date
finishing = Finishing Date
booking = Booking Date
sale = Sale Date
date=Date
type=Type
selectOneUnitMsg=Select at least one unit to save.
errorMultiSaveMsg=Could not save for some units, may be it was saved previously.
successSaveMsg=Saved Successfully.
 
unitSearch = Search For Unit 
area = Area 
project = Projects
unitArea = Unit Area 

followa2 = The Desires
followb2 = The Project
followc2 = the Area
followd2 = Payment System
followe2 = Duration
followf2 = Time Added
followg2 = Source
followh2 = Notes
followi2 = Reviews
followj2 = Reservations
followk2 = Units
followl2 = The Project
followm2 = The Area
follown2 = The Price
followo2 = Description
followp2 = Payment System
followq2 = Duration of Reservation
followr2 = Type Of Reservation
follows2 = Time Added
followt2 = Source

followa3 = Units
followb3 = The Project
followc3 = Description
followd3 = The Area
followe3 = The price
followf3 = Time Added
followg3 = Source

followa4 = Project
followb4 = Building
followc4 = Unit Type
followd4 = Area
followe4 = Price
followf4 = Per Cent
followg4 = Amount
followh4 = Payment System
followi4 = Receipt No
followj4 = Source Client	
followk4 = Broker Name	
	

followa5 = Reservation Unit
followb5 = Data Sheet Unit
followc5 = Land Area
followd5 = The Model
followe5 = Only
followf5 = Only
followg5 = Price Unit
followh5 = Price Before Discount
followi5 = Floor Of Unit
followj5 = Area  Unit
followk5 = Code  Unit / Villa
followl5 = Data Sheet Reservation 
followm5 = Duration Of Reservation
follown5 = Only
followo5 = Only
followp5 = Receipt NO.
followq5 = Additions
followr5 = Payment Plan
follows5 = Payment for Reservation 
followt5 = Contract Payment 
followu5 = Date Reservation
followv5 = Data Sheet Reservation
followw5 = Reservation NOW 
followx5 = Sales Manager


followa6 = Code Unit
followb6 = Sales Mang.
followc6 = Client
followd6 = Mobile
followe6 = Phone Roaming
followf6 = Duration Of Reservation
followg6 = Date Reservation
followh6 = Type Of Reservation
followk6 = The Remaining Time
followl6 = Reservation Form
followm6 = Normal Reservation
follown6 = Reservation canceled 

unitcode = unitcode
SalesMang = Sales Mang.
ReservationForm = "Reservation Form"
TheRemainingTime = "The Remaining Time"
TypeOfReservation = "Type Of Reservation"
DateReservation = "Date Reservation"
DurationOfReservation = "Duration Of Reservation"
Client = "Client"
Mobile = "Mobile"
PhoneRoaming = "Phone Roaming"
 
payPlan = Payment Plan 
delDate = Delivery Date 
clientDetails = Client Information  
chsClient = Choose Client
clientName = Client Name 
clientJob = Client Job 
clientMob = Mobile No.
clientPhone = Phone No.
clientNat = Nationality 
clientIntNo = International No. 
clientAdd = Address
clientEmail = Email 
payPlanDetalis = Payment Plan Details 
planTitle = Plan Name 
reservation = Reservation 
downPay = Down Payment 
installments = Installments 
installmentsSystem = Installments System 
insNum = Within 
discount = Discount 
warnningMsg = Choose Reservation Date 
insPrice = Installment Amount
paymentDetalis = Payment Details

payPlanSys = Payment Plan System 

standPlan = Standard Payment Plan 

garage = Garage 
locker = Locker 

prjDetails = Project Details
locker = Locker 

available=Available
reserved=Reserved
sold=Sold
hidden=Hidden
total=Total
percent=Sales Ratio
region=Region
allSpaces=All Spaces
lessThan=Less than
moreThan=More than
inDescription=Search in Desc.
regionMsg=Select a region.
owner=Owner
accurateUnitSearch=Accurate Search for Unit
priceTip=Meter Price Tip
none=None
clientNo=Client No.
to=To
mobile = Mobile No
subject=Subject
details=Unit Details
messageBody=Message Body
messageContent=Message Content
send=Send
clientNoWrongMsg=Client No. is Wrong
emailSuccessMsg=Email sent Successfully
emailFailMsg=Email Sending Fail
sendAllImage=Send All Images
unitTypeRequiredMsg=Select Unit Type

delUnits = Update Status Units 

editMdl = Edit Model 
deleteConfirm=Update, Are you sure?

purchaseMsg=Cannot delete unit already sold.
reservedMsg=Cannot delete unit already reserved.
deleteConfirm=Delete, Are you sure?

area = Area

timeLine = Time Line 
dateType = Date Type 
date = Date 

priceFrom = Price From 

resVal = Reservation Value
firstPay = First Payment
fPAfter = First Payment After
fAfter = Payment After
paymentSys = Installment System
month = Month/s
title = Payment Plans
planTit = Plan Title
dir = LTR
statusTit = Status
client = Client
employee = Employee
creationTime = Creation Time
paymentP = Payment Plans
resDate = Reservation Date
or = or
fIDate = First Installment Date 
installment = Installments
title2 = Standard Payment Plans
defaultPrice=Default Price
title2 = Standard Payment Plans
resDetails = Reservation
instDetails = Installment
unitpriceD = Unit Price After Discount
genplan = Generate Payment System
min = Min
max = Max
after = After
month = Month-s
calc = Calculate Installment Value 
gPaymentPlan = Generate Payment Plan
msgalrt = Please You Must Calculate Installment Value First
note = Notes
createdBy = Created By
creationTime = Creation Time
noPlanAlert = Please Select Main Plan
dualInstDetails = Monthly Installment
yearlyInstDetails = Second Installment
yearlySys = Yearly installment type
yearlySysInsVal = installment value
dualTitle = Dual Payment Plans
monthCalc = Calculate Monthly Installment
dur = Duration
yearlyCalc = Calculate Second Installment
fmsg=Failed to Save
smsg=Successfully Saved
addsTitle=Unit Add Ons
Garden=Garden
Garage=Garage
Roof=Roof
AddOnsType=Add On Type
onPrice=Price
onArea=Area
onUnit=Unit
level=Level
addOnsT=Unit Add Ons
AddonType=Type
AddOnPrice=Price
AddOnArea=Area
EditAddOn=Edit
RemveAddOn=Remove
level=Level
floor=Floor
grossArea=Gross Area
gardenArea=Garden Area
terraceArea=Terrace Area
garageArea=Garage Area
addonPrice=Add-on Price
forProject=for Project
forUnit=for Unit
installmentsNo=Installments No
AddonType=Type
AddOnPrice=Price
AddOnArea=Area
EditAddOn=Edit
RemveAddOn=Remove

levelu=Level 
unitDes=Unit Description
projects=projects
model=Model
noCmodel=Please Select Model
addGarages=Add Garages
garageGeneratedMsg=Garages generated successfully
failToGenerateMsg=Fail to generate garages
garageNoRequiresMsg=Garages No. is required
projectDesc=Project Description
reserve=Reserve