direction=ltr
align=left
dir=rtl
# sales_market.jsp

calls_meetings=Calls/Meetings
depreqs=Department Requiremts
notif=Notifications
myorders=My Customers
#search_for_client.jsp
search=Search
clientno=Customer Numbers
clientno_placeholder= phone/mobile/international
incorrect_clientno=Incorrect Customer Number
incorrect_phone=Incorrect Phone Number
incorrect_mobile=Incorrect Mobile Number
chooseclient=Choose Customer
clientname=Customer Name
noclient=Customer name is not exist
clientstatus=Customer Status
viewfiles=Show Files 
details=Details
view=View
contentsearch=Enter content search

# add employee new_client.jsp
tittle=New client registration
number=Customer number
name=Name
phone=Broker Phone
mobile=Mobile
dialled=Dialled Number
intnumber=International Number
wifehusband=Broker Name
city=Country  
gender=Gender
career=Career
nationality=Nationality
status=Phone
branch=Branch
address=Address
notes=Notes
workabroad=Work Abroad
mail=E-mail
isrelativabroad=Relatives abroad
projects=Projects
within= within (year)
payment=Payment Method
area=Area
single=Single
married=Married
unspecified=UnSpecified
divorsed=Divorced 
yes=Yes
no=No
cash=Cash
installment=Installment
male=Male
female=Female
knowus=Know Us Through
choose=Choose
egy=Egyptian
saudi=Saudi
american=American
polish=Polish
addjob=Add Career
addreg=Add Region
clientSource=Customer Source
select=Select
add=Add
seasonCode=Code
seasonName=Name
#sales_market_closed.jsp
code = Region Code
request =Request
requestno=Order No.

reqdate=Date 
resp=Responsible
type=Customer Type
requeststatus=Status
reqtype=Type
today=Today
showsince=Show Since
hour=Hour
twohour=2 Hours
threehour=3 Hours
day=Day
twoday=2 Days
threeday=3 Days
week=Week
month=Month
twomonth=2 Months
unspecified=UnSpecified

#sales_market_dep.jsp
source=Source
calldate=Call Date
calltype=Call Type
callerno=Caller No.
calldirec=Call Direction
callscount=Calls/Reqs No

#new_Company
compcode=Company Code
compname=Company Name
region=Region
buisness=Business Sector
active=Active
addregion=Add Region

company = New Company
client = New Customer

clientId = Customer Number

contentsearchln = Minimum three characters

 campgin =  Campgins/Campgins Tools

fromDate=From Date
toDate=To Date
search=Search
email=Email

myCustomerComments=My Customers' Comments
clientCommentMsg=Last 3 Days' Comments

localMobile= Local
interMobile=International
Mobile=Mobile Type

createdBy=Created By
creationTime=Creation Time