# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

to=To
subject=Subject
text=Text
send=Send
attach=attach file
mobileno=Mobile No.
addfile=Add File
showfiles=Show Files
upload=Upload
tittle=Tittle
type=Type
username=User Name
nofiles=No Files
date=Date
delete=Delete
direction=ltr
addcomment=Add Comment
showcomments=Show Comments
commenttype=Comment Type
public=Public Comment
private=Private Comment
comment=Comment
save=Save
commentadded=Comment is added Successfully
nocomments=No Comments
addmeeting=Add Meeting
showmeetings=Show Meetings
client=Client
target=Target
call=Call
location=Location
meetingadded=Metting is added Successfully
align=left
followup=Follow-Up Clients
employee=Employee
result=Follow Up Result
date2=Date
edit=Edit
nomeetings=No Meetings
follow=Follow-Up Client
meeting=Meeting
addgift=Add Gift
showgifts=Show Gifts
close=Close
deleteMsg=Delete Comment, Are you sure?
answered = Answered
nanswered = Not Answered

attended = Attended
nattended = Not Attended
duration = Duration
notes = Notes
type1=Follow Up Type
source=Source