direction=ltr
align=left
attachments=Attachments
code=Code
address=Address
status=Status
manager=Manager
responsilbe=Responsible
taskstatus=Task Status
notify=Notify
close=Close
comment=Comment
distribution=Distribution
re-distribution=Re-Distribution
cancle=Cancle
requeststages=Reguest Stages
print=Print
delete=Delete
css-requsetstages=en-requsetstages
css-notify=en-notify
css-attach=en-attach
css-comment=en-comment
css-close=en-close
css-distribution=en-distribution
css-redistribution=en-redistribution
css-cancle=en-cancle
css-print=en-print
css-delete=en-delete
save=Save
folloNo=Order No.
topic=Topic
source=Source
callage=Contact Since
regdate=Registration Date
emplname=Employee Name
notes=Notes
client=Client
custstatus=Client Status
clientname=Client Name
clientno=Client No.
clientrating=Client Rating
css-email=en-email
email=Email
css-sms=en-sms
sms=SMS
css-meeting=en-meeting
meeting=Meeting
campaigns=Campaigns
css-campaigns=en-campaigns
css-gift=en-gift
gifts=Gifts
units=Units
purchases=Purchases 
unit=Unit
project=Project
details=Details
bookings=Bookings
desires=Interests
payment=Payment
bookduration=Booking Period
bookdate=Booking Date
booktype=Booking Type
area=Area
duration=Duration
sellunit=Sell Unit
css-sellunit=en-sellunit
bookunit=Book Unit
css-bookunit=en-bookunit
Nofollow = No. Follow Up
request = Request
means = By Means
date = By Date
comment1 = Comment
Commenttype = Comment Type
