direction=ltr
input = Incoming
output = Outgoing
foryourinfo = F.Y.I
 notification=Notification
finished=Finished
showsince=Show Since
hour=Hour
twohour=2 Hours
threehour=3 Hours
day=Day
twoday=2 Days
threeday=3 Days
week=Week
month=Month
twomonth=2 Months
unspecified=UnSpecified
request =Request
requestcode=Request code
requestno=Order No.
clientname=Client Name
callingdate=Date
reqdate=Date
status=Status
source=Source
sender=Sender
direction=ltr
align=left
type=Type
mobile=Mobile
address=Address
notes=Notes
remaintime=Remaining Time
recently=Recently Incoming
fromDate=From Date
toDate=To Date
search=Search
supervisorComments=Supervisor Comments
distdate= Distribution Date
activeComments= Urgent  
alignX=right
upadteAppointment=Update Appointment
appointmentNo=Appointment No.
employee=Employee
appointmentDate=Appointment Date
branch=Branch
comment=Comment
save=Save
selectEmployeeMsg=Select Employee
commentRequiresMsg=Comment is Required
failMsg=Fail to Save
update=Update
cancel=Cancel
emp_req=Holidays Request
My_req=My Holidays Requests
futureAppointments=Future Appointments
appointmentdate=Appointment Date