width=1000px
align =left
details= Client Info 
dir =LTR
style =text-align:left
noClientExistMsg =No Client Exist for this Number or Number is not Valid or you have no Authority to view client's details
clientid=Client ID
followcl = Follow Up Client
followa1 = Type of follow-up
followb1 = Follow-up status
followd1 = Duration
followe1 = Result of follow-up
followf1 = Comment
followg1 = Minute
 
        
phone=Phone No.
call=Call
clientname=Client Name
wifehusband=Name
birthdate=BirthDate
gender=Gender
male=Male
female=Female
socialstatus=Phone
id=National ID/Passport
job=Career
region=Region
notes=Notes
mail2=Another Email
Custmmov=Customer Dynamics
status=Status
source=Source
employee=Responsible Employee
direction=rtl
lastedit=Last Edit
signindate=SignIn Date
editdate=Edit Date
phone2=Another Phone No.
branch=Branch
mobile=Mobile No.
internumber=international number
address=Address
email=Email
isworkabroad=Working abroad
isrelativabroad=Relatives abroad
nodata=No Data
noselection=No choice
single=Single
married=Married
unspecified=UnSpecified
divorsed=Divorced
cllaingno=Clling No.
yes=Yes
no=No
noRating=No Rating
clientRating=Client Rating
knowUs=Know Us Through
select=Select
fromDate=From Date
toDate=To Dates
clientNo=Client No.
campaignTitle=Campaign Title
failMsg=Fail to Save
clientCampaigns=Client Campaigns
addCampaign=Add Campaign
sat=Sat
sun=Sun
mon=Mon
tue=Tue
wed=Wed
thu=Thu
fri=Fri

spareParts = Spare Parts 
rawMaterials = Raw Materials 
workers = Workers 
mItems = Maintenance Items 
actionItems = Work Items 

viewMyOrder = View Order 

jobOrderProcessing = Job Order Processing 
addMWork = Maintenance Items 
addBWork = Work Items 
orderInvoice = Job Order Invoice 
orderstatus = Order Status 
creatorName = Issuer  
creationTime = Request Time 
itmCode = Code 
itmName = Title 
numUnit = #Units 
itmRate = Unit Rate 
itmPrice = Cost 
totalPrice = Total Cost 
jobOrderDetails = Job Order Details 
orderID = Order ID 
orderItms = Order Items 
owner = Owner 
sysDate = Date 
billTo = Bill To 
bPrice = Work Items Cost 
mPrice = Maintenance Items Cost 
sprPrtCost = Spare Parts Cost 

interests = Client Interests
lockedTo=Locked to
lockedBy=Locked by
lockDate=Lock Date
userAppointment=Employee Appointment
theEmployee=The Employee

showmaps= Show Client Locations