direction=ltr
align=left
 
organizationtree=Organization Structure
all=All

prjArea = Project Area Association
area = Area
add = Add
projects = Projects
selectAreaMsg = Select an Area
selectPrjMsg = Select a Project

sprPrtNum = Spare Parts Number 
code = Code 
sprPrtName = Spare Part Name 
cst = Cost 
quantity = Quantity 