Insert into PROJECT values ('1414239210597','ريجينسى','REG',to_date('25-OCT-14','DD-MON-RR'),'1','ريجينسى','1364111290870','44','1','UL','UL','UL','UL','0','0',null,null,'1');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('1', 'شوقى عبدالله شكرى اباظه', '40', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('2', 'ضياء منير ايليا جيد', '35', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('3', 'شيرين احمد ابراهيم عبدالبارى', '01', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('4', 'احمد عمر محمد عمر عامر', '01', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('5', 'عمرو رجب عباس', '39', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('6', 'ايمن احمد عبد العزيز الخولى', '36', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('7', 'عزة صبحى توفيق', '41', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('8', 'هشام حسين عبدالمنعم / سناء محمد محى الدين', '02', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('9', 'احمد عوض احمد', '41', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('10', 'احمد فهيم مصطفى ماهر', '40', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('11', 'مينا نبيل كامل حنا', '01', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('12', 'احمد محمد منير محمود امام', '35', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('13', 'تميم حلمى محمد محمود شكر ', '02', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('14', 'ايهاب محمد شلبى / ياسر محمد شلبى', '39', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('15', 'مى حسام الدين عبد الوهاب شوشة', '37', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('16', 'احمد محمد محمد السيد ', '36', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('17', 'هانى محمود عبدالعال محمد', '35', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('18', 'محمد محمود عبد الحميد عبد الواحد', '40', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('19', 'محمد محمود عبد الحميد عبد الواحد', '40', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('20', 'حسام حلمى محمد وهبة', '36', '36');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('21', 'محمد حلمى محمد محمود شكر ', '02', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('22', 'شرين مصطفي مصطفي احمد', '39', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('23', 'اسامه عبدالقادر احمد منصور', '34', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('24', 'محمد احمد مهنى عثمان ', '36', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('25', 'محمد مصطفى محمد ابراهيم القاضى ', '34', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('26', 'كريم احمد سيد عباس', '34', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('27', 'محمد احمد عبد المعطى اسماعيل', '40', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('28', 'مها محمود سمير / محمد محمود لبيب', '38', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('29', 'ايريس كريكور غرابيت قيصر ليان', '39', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('30', 'اشرف حسن عبدالقادر', '41', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('31', 'محمد محمود سمير النبراوى', '39', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('32', 'احمد عبد السميع عبد الله', '37', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('33', 'محمد محمود سمير النبراوى / نيهال محمد كمال', '36', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('34', 'رشا حلمى محمد شكر ', '02', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('35', 'وليد احمد كامل مهنى', '01', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('36', 'احمد عبد الحافظ عبد الوهاب', '36', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('37', 'فاطمة محمد عبد الله ', '36', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('38', 'مها فاروق محمد محمد زكى شلبى', '40', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('39', 'احمد فخرالدين محمد محمد', '41', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('40', 'شريف عبدالله عبدالعزيز', '38', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('41', 'احمد عبد العزيز صبحى اسماعيل والي', '35', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('42', 'سماح فوزى عطا الله ذكرى', '01', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('43', 'صلاح صالح عبدالهادى - جيهان محمد عبدالخالق', '39', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('44', 'مى صلاح الدين الايوبى', '01', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('45', 'مى صلاح الدين الايوبى', '02', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('46', 'سارة محمد نبيل عمر ', '41', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('47', 'على السيد قاسم الطنطاوى', '40', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('48', 'محمد فاروق على محمد', '41', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('49', 'محمد طلعت بدر السيد', '34', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('50', 'محمد احمد محمد السرى', '41', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('51', 'ايه صلاح الدين الايوبى محمد امام', '39', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('52', 'امير طارق مرسى مرسى', '02', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('53', 'تامر عزالدين احمد سالم', '37', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('54', 'محمود السيد محمود السيد', '35', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('55', 'محمود متولى السيد', '40', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('56', 'احمد عمار ابراهيم', '39', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('57', 'محمد السيد حسين', '01', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('58', 'عمر لطفى يس', '01', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('59', 'مينا ميخائيل عزيز نجيب', '39', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('60', 'حسن مصطفى حسن', '38', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('61', 'ادهم فوزى محمد', '35', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('62', 'محمد عطا عبدربه', '01', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('63', 'هيثم عبدالهادى السيد ', '34', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('64', 'وائل محمد رفعت دياب', '36', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('65', 'وسيم عادل نجيب', '38', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('66', 'جمال عبدالله عبدالعال', '37', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('67', 'منال محمد على عبد الجواد', '38', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('68', 'رامى عصام عبدالرحيم حسان السيد', '34', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('69', 'محمد عبدالعليم علي محمد', '40', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('70', 'تيمور أحمد حسن علي عبد الحليم صقر', '02', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('71', 'كريم محمد عصام الدين عبد الظاهر ', '35', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('72', 'تامر محمد عبدالمنعم', '34', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('73', 'مى محمد شوقى', '39', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('74', 'ايمان على محمد الجبلى / طارق محمد ', '36', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('75', 'هالة رضا عبدالله', '02', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('76', 'الشريف حسن محمد السعيد', '34', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('77', 'حسام الدين محمد صادق', '38', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('78', 'عز الدين شحاته سرور', '34', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('79', 'عماد الدين محمد ابراهيم', '39', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('80', 'احمد محمد كمال', '35', '35');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('81', 'كريم يسرى عبدالجليل', '02', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('82', 'ياسر على سعيد المهلهل', '35', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('83', 'محمد ياسر احمد', '34', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('84', 'مروة حسين محمد ابراهيم', '37', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('85', 'هبة الله محمد على / جودى محمد على', '02', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('86', 'معتز فيصل عبدالمجيد', '39', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('87', 'ممدوح احمد محمود رزق', '36', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('88', 'محمد بيومى حسنين', '34', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('89', 'ايهاب عبدالله عوض', '36', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('90', 'وليد محمد فتوح البرماوى', '35', '36');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('91', 'احمد محمد السيد سعد بدار', '38', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('92', 'ياسمين اشرف ابراهيم / مريم اشرف ابراهيم', '37', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('93', 'عبدالحميد عباس عبدالحميد', '36', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('94', 'محمد محمد عكاشة', '37', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('95', 'نهال احمد عبدالمجيد', '37', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('96', 'احمد عبد التواب احمد محمد عبد الله', '35', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('97', 'يحى سعيد محمد الحلوانى', '34', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('98', 'كمال محمد عبدالحميد البحر', '34', '36');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('99', 'عبدالله ابراهيم ابراهيم', '38', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('100', 'احمد عبدالسلام عبدالرشيد-اميرة محمد على', '34', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('101', 'وليد سيد محمد جمعة', '37', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('102', 'هشام فتوح محمد عبدالرحمن', '34', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('103', 'امجد فتحى عبدالنور غبريال', '39', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('104', 'بنان رضوان عبدالموجود', '37', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('105', 'سهير عبدالسلام', '01', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('106', 'احمد اسماعيل محمود الجندى', '01', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('107', 'داليا عبدالفتاح الفقى', '40', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('108', 'عصمت محمد جميل', '41', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('109', 'عمرو كمال محمد السيد ابراهيم', '01', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('110', 'سارة صلاح على محمد', '02', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('111', 'محمود هشام حامد بهنساوى ', '33', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('112', 'تامر سمير غالى فرج ', '29', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('113', 'محمد بكر الصديق ابراهيم', '33', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('114', 'صبرى حامد طلبة', '39', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('115', 'عماد الدين محمد عبدالوهاب', '40', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('116', 'عماد ثروت محمود المهيلمى', '29', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('117', 'عماد ثروت محمود المهيلمى', '29', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('118', 'محمود فتحى ابراهيم خليل', '33', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('119', 'محمد علاء الدين على', '20', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('120', 'منة الله احمد حسن - آية احمد حسن', '33', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('121', 'عبدالله مصطفى محمد ابراهيم', '40', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('122', 'ايمن محمود محمد', '37', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('123', 'محمد عبدالبصير الزناتى هيكل ', '34', '35');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('124', 'وليد عبدالوارث عبدالله', '33', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('125', 'محمد صلاح سيد', '35', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('126', 'احمد حسين حلمى اسماعيل سلامه', '36', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('127', 'ابراهيم فاروق ابراهيم يحيى ', '33', '36');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('128', 'نيفين محمود اسماعيل', '33', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('129', 'وهبة عزمى وهبة يونان', '33', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('130', 'محمد مجدى مصطفى رشدى صالح ', '33', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('131', 'اشرف احمد حسن درويش', '29', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('132', 'محمد عبدالرحيم على', '32', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('133.0', 'مها يحى عيسى سيسالم', '40', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('134.0', 'مها يحى عيسى سيسالم', '29', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('135.0', 'صفوان عادل السيد', '35', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('136.0', 'نادية محمد محمد الحسينى', '29', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('137.0', 'انور محمد سيد على', '29', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('138.0', 'عادل عبدالكريم محمد محمد', '29', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('139.0', 'كريم عزمى صادق عبد الشهيد / جيهان سمير صالح صبحي ', 'TH I-3', 'TH I-3');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('140.0', 'عبد الوهاب احمد عبدالوهاب', '40', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('141.0', 'تميم ابراهيم احمد ابراهيم', '32', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('142.0', 'دعاء عبدالله مصطفى', '39', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('143.0', 'ايهاب احمد احمد الكردانى ', '33', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('144.0', 'رانية عبدالله محمد سعيد', '32', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('145.0', 'مصطفى محمود عبدالله الجلاد ', '37', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('146.0', 'جورج عبدالفادى ناشد', 'TH II-2', 'TH II-2');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('147.0', 'فاروق عبدالجواد محمد دنيا', '32', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('148.0', 'مصطفى عبدالحميد مصطفى علام', '30', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('149.0', 'امل محمد حسن عيسى', '30', '36');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('150.0', 'هبة الله عدلى صالح رجب', '38', '36');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('151.0', 'لبنى محمد سمير', '38', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('152.0', 'احمد محمد حسن', '41', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('153.0', 'محمود فاروق فراج عبد الرحمن ', '29', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('154.0', 'حسين الامام على محمد محرم ', '30', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('155.0', 'ابراهيم احمد صبرى عبد الجليل ', '30', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('156.0', 'حمدى احمد طه غريب', 'TH 51-2', 'TH 51-2');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('157.0', 'احمد عبد الرحيم موسى', '38', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('158.0', 'محسن محمد ادريس السنوسى', '02', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('159.0', 'عماد الدين على عبدالتواب عبد الفتاح ', 'TH I-2', 'TH I-2');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('160.0', 'مينا لطفى توفيق', '35', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('161.0', 'احمد عوض الشربينى/داليا السيد محمد المنسى الشال ', 'TH I-1', 'TH I-1');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('162.0', 'محمد احمد محمود ابوالقاسم', 'TH I-4', 'TH I-4');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('163.0', 'على محمد على الخوار النعيمى ', 'TH 5 -2', 'TH 5 -2');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('164.0', 'اكمل عبدالحكيم حمدى الطوبجى', 'TH 5 -1', 'TH 5 -1');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('165.0', 'ايمن محمود نيازى سليمان محمد الشيخ ', 'TH 51-1', 'TH 51-1');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('166.0', 'جمال عبده احمد ابراهيم', 'TH II-3', 'TH II-3');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('167.0', 'على حسن على احمد الشافعى', 'TH II-1', 'TH II-1');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('168.0', 'احمد عبد العزيز سيد حسن ', '38', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('169.0', 'وائل سليمان طه سليمان', '38', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('170.0', 'رشا سعيد عيسى حسن', '30', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('171.0', 'عادل حازم مصطفى كمال / مصطفى حازم مصطفى ', '33', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('172.0', 'رقية عطية الله غاندى', '29', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('173.0', 'خليل محمد احمد سيف', '29', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('174.0', 'هدى عباس سيد عبد الباقى ', '29', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('175.0', 'اشرف احمد شوقى المحروقى', '35', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('176.0', 'تامر احمد شوقى المحروقى ', '36', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('177.0', 'ساتى بشير ساتى', '32', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('178.0', 'ماجدة محمد حسن امين  الكاشف ', '30', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('179.0', 'حسن محمد حسن امين الكاشف', '32', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('180.0', 'محمد محسن زينهم زكى عبد العال ', '29', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('181.0', 'محمد بدوى احمد صالح', '40', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('182.0', 'رضوى بدوى احمد صالح', '32', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('183.0', 'خالد الهامى عبدالباقى ابوالقاسم', '33', '35');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('184.0', 'منال عبد السلام حسنى نجيب ', '34', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('185.0', 'ايمن السيد عبد الخالق محمد', '33', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('186.0', 'راما / احمد / سلمى ماهر محمد عبد الحكيم', '36', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('187.0', 'زياد عبد الحكيم عطية محمد الغانم(بولاية ولده )', '33', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('188.0', 'محمود عبد الحميد على فرج ', '30', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('189.0', 'عصام احمد محمد محمود سيف ', '01', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('190.0', 'هشام فتوح محمد عبدالرحمن', '02', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('191.0', 'عمر محمد حسن صبيح', '01', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('192.0', 'مايسة محسن مصطفى ابو بكر ', '36', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('193.0', 'سامح ابو بكر بكارسلام', '38', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('194.0', 'تامر سمير محمود هانى', '37', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('195.0', 'عمرو صلاح رجب', '41', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('196.0', 'عمرو صلاح رجب', '41', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('197.0', 'تامر محمود السيد ابراهيم (ايمان ابراهيم البسطويسى ', '32', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('198.0', 'محمد على جمال الدين', '35', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('199.0', 'حاتم عبد الاخر عبد الفتاح عبد الاخر ', '30', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('200.0', 'داليا على فتحى نجيب', '41', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('201.0', 'عبد الفتاح عبد الاخر عبد الفتاح  عبد الاخر ', '34', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('202.0', 'منال مصطفى مختار محمد ', '41', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('203.0', 'محمد جمال عبد العال عبد النبى ', '36', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('204.0', 'محمد ابراهيم محمد على- رحاب عبد الحميد محمد', '34', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('205.0', 'وائل عطية طة على', '35', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('206.0', 'فاطمة حسنين على سالم', '02', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('207.0', 'محمد فتوح امام عبد الفتاح ', '33', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('208.0', 'احمد حازم احمد نور ', '39', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('209.0', 'اسلام مصطفى عواد', '32', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('210.0', 'عمرو عبد الفتاح  عبد العظيم بركة', '35', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('211.0', 'رامى ممدوح محمد القدوس', '02', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('212.0', 'محمد محسن محمد عبد الرحمن', '30', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('213.0', 'بليغ حمدى عبد الفتاح حسن الدجاج ', '29', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('214.0', 'هبة عبدالحميد عبدالحميد محمد', '30', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('215.0', 'اسلام محمود عبد الجواد رجب ', '01', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('216.0', 'احمد عبد الكريم احمد عبد الكريم', '34', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('217.0', 'رشا بدوى على سعد خليفة', '32', '35');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('218.0', 'خالد احمد سامى جودة نجم ', '37', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('219.0', 'هالة بدوى على سعد', '33', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('220.0', 'ماجده احمد حلمى قبيصى ', '33', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('221.0', 'معتز احمد عبد الفتاح شقير', '29', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('222.0', 'هشام مصطفى عواد', '32', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('223.0', 'معتز احمد عبد الفتاح شقير', '29', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('224.0', 'عمر السيد عمرو فتح الله عبد الرحمن ', '30', '22');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('225.0', 'يحى نبيل على احمد حنفى', '32', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('226.0', 'يحى نبيل على احمد حنفى', '32', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('227.0', 'صفوان محمد عبد اللطيف', '29', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('228.0', 'حسن عبد الحميد حسن السنباوى ', '30', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('229.0', 'حاتم محمد عمر محمد الشناوى ', '32', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('230.0', 'سامى عبد العزيز حسن المصرى ', '02', '32');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('231.0', 'احمد البدرى محمد عبد الله', '38', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('232.0', 'خالد حسنى سيد الاهل', '30', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('233.0', 'محمد عبد الرحمن محمود محمد', '37', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('234.0', 'يسرى عبدالله احمد مشهور ', '38', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('235.0', 'اسلام السيد عبد العزيز - ندى محمد ابرهيم حسن يوسف', '34', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('236.0', 'بروين محمد ابراهيم', '34', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('237.0', 'عمرو حازم فريد عباسى ', '41', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('238.0', 'احمد صابر عبد السميع', '36', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('239.0', 'عمرو موسى ابراهيم موسى', '29', '36');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('240.0', 'محمد القاضى رمضان حميدة خليفة ', '29', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('241.0', 'وليد سامى جابر عبد اللطيف', '40', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('242.0', 'احمد ممدوح كامل شبيطة - ماجد ممدوح كامل شبيطة ', '41', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('243.0', 'اشرف مرسى محمد مرسى عمار ', '30', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('244.0', 'دينا محمد طلايع محمد مصيلحى ', '36', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('245.0', 'عمرو حسين العزب احمد العزب ', '35', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('246.0', 'لمياء محمد سيد احمد منصور', '35', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('247.0', 'محمد عبد الحميد درويش محمد خيرى ', '01', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('248.0', 'محمد اسماعيل شريف عبد الغنى سلطان', '38', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('249.0', 'تامر ايهاب ادوار الخراط', '41', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('250.0', 'احمد لطفى عبد العال حسين ', '38', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('251.0', 'احمد عبد العظيم بسيونى ', '33', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('252.0', 'احمد احمد حاتم محمد ', '29', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('253.0', 'اميره عبد السلام مصطفى ', '35', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('254.0', 'اميره عبد السلام مصطفى ', '35', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('255.0', 'ياسر طه محمد مرسى', '20', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('256.0', 'احمد عزت حلمى السيد', '20', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('257.0', 'منال رحيم محمد ابراهيم', '36', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('258.0', 'تامر فتحى توفيق ابراهيم ', '33', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('259.0', 'عبد الله محمد سعيد نور الدين ', '32', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('260.0', 'جيهان سعد الدين محمد حابك', '37', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('261.0', 'شريف محسن عبد المنعم خريبة ', '31', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('262.0', 'هيثم عصام بكر السيد ', '36', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('263.0', 'اشرف حسين احمد عبد الله ', '20', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('264.0', 'يسرى عبدالله احمد مشهور ', '31', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('265.0', 'احمد رجب عبد المحسن عبد الحافظ', '37', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('266.0', 'عادل لطفى رمضان صالح', '31', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('267.0', 'خالد هشام حامد بهنساوى ', '30', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('268.0', 'عمرو احمد صالح زنباعى', '31', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('269.0', 'كريم حسين عبد المنعم حسين', '38', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('270.0', 'احمد صالح حسن صالح', '20', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('271.0', 'يسرا - ياسمين - نادين عماد الدين على مصطفى على ', '31', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('272.0', 'مروان احمد جابر ', '20', '12');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('273.0', 'مروان احمد جابر ', '30', '21');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('274.0', 'مروان احمد جابر ', '30', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('275.0', 'مروان احمد جابر ', '32', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('276.0', 'مروان احمد جابر ', '20', '26');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('277.0', 'مروان احمد جابر ', '36', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('278.0', 'مروان احمد جابر ', '32', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('279.0', 'وفاء احمد مجاهد', '33', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('280.0', 'وفاء احمد مجاهد', '38', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('281.0', 'محمد ابو بكر سليمان', '20', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('282.0', 'على نبيل محمد عبد العال ', '31', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('283.0', 'امل السيد محمد العزوبى', '31', '33');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('284.0', 'امل السيد محمد العزوبى', '31', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('285.0', 'طارق مصطفى عبد القادر البندارى ', '38', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('286.0', 'حسن جلال فائق حسن', '35', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('287.0', 'كريم ايهاب محمد على جبر برعى(بولاية الوالد) ', '31', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('288.0', 'تامر محسن محمد الشوربجى ', '37', '06');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('289.0', 'تامر محسن محمد الشوربجى ', '31', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('290.0', 'جاسمينا محمد سعيد محمد نور الدين ', '30', '02');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('291.0', 'حسن طارق عبد العزيز الجمل', '34', '16');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('292.0', 'عمرو عاطف محمود العوضى', '31', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('293.0', 'محمد ابراهيم محمد على- رحاب عبد الحميد محمد', '31', '14');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('294.0', 'احمد فتحى عبد الوهاب', '29', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('295.0', 'احمد محمد عباس مصطفى - سارة فرج فتحى فرج', '30', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('296.0', 'كمال كمال محمد هارون - احمد محمود محمد الوكيل', '32', '01');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('297.0', 'نورهان سيد طلبة يونس', '37', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('298.0', 'عفاف احمد على عبد الهادى', '31', '31');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('299.0', 'محمد صلاح الدين منير عمران', '29', '11');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('300.0', 'محروس فوزى سليم الدمرداش', '31', '13');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('301.0', 'حسنى عبد الله عبد السميع حسن عويس', '20', '15');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('302.0', 'سليم تامر محمد جلال حامد بولا ية الوالد /تامر محمد', '32', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('303.0', 'نرمين جميل فائق حسن فائق', '32', '05');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('304.0', 'ايمان محمد احمد رمضان', '33', '03');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('305.0', 'محمود حسن البنا حسين السيد / مها عبد الحميد حسن ', '31', '25');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('306.0', 'احمد سامى منجود نصار', '33', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('307.0', 'وفاء محمد ابراهيم القصراوى ', '20', '23');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('308.0', 'عمرو محمد ابراهيم', '32', '24');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('309.0', 'مصطفى محمود عبد الحميد محمد', '31', '04');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('310.0', 'محمد عماد الدين ابراهيم عامر غنيم', '38', '35');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('311.0', 'شادى احمد شيلابى فيصل', '33', '34');

INSERT INTO REGENCY_UNITS (FORM_NO, CLIENT_NAME, BUILDING_CODE, UNIT_CODE) 
VALUES ('312.0', 'عماد محمد حسن احمد ', '31', '15');


