/*
 * MenuBuilder.java
 *
 * Created on January 8, 2004, 6:33 AM
 */

package com.silkworm.business_objects.secure_menu;

import com.silkworm.business_objects.DOMFabricatorBean;
import com.silkworm.servlets.GroupServlet;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.StringWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 * Created by IntelliJ IDEA.
 * User: Walid
 * Date: Jan 25, 2003
 * Time: 12:21:55 PM
 * To change this template use Options | File Templates.
 */
public class MenuBuilder {
    private ThreeDimensionMenu menu = null;
    private String fileURL = null;
    private String xslFile = null;
    private String xslGroupFile = null;
        
    public  MenuBuilder() {
        
    }
    public ThreeDimensionMenu getMenu() {
        
        if(menu == null && fileURL!=null) {
            try {
                System.out.println("Fatawakal 3ala Allah");
               //menu  = new TwoDimensionMenu(DOMFabricatorBean.getDocument(fileURL));
               menu  = new ThreeDimensionMenu(DOMFabricatorBean.getDocument(fileURL));
                return menu;
            }
            catch(Exception e) {
                System.out.println("Could not locate XML Document");
                return null;
                
            }
        }
        return null;
    }
    public void setMenu(String mFile) {
        
        
    }
    
    public void setFileURL(String mFile) {
        fileURL = mFile;
        
    }
    
    public String getFileURL() {
        return fileURL;
    }

    public String getXslFile() {
        return xslFile;
    }

    public void setXslFile(String xslFile) {
        this.xslFile = xslFile;
    }

    public String getXslGroupFile() {
        return xslGroupFile;
    }

    public void setXslGroupFile(String xslGroupFile) {
        this.xslGroupFile = xslGroupFile;
    }
    
    public String buildMenu(String xmlString){
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        Document document;
        StringWriter outWriter = new StringWriter();
        //factory.setNamespaceAware(true);
        //factory.setValidating(true);
        try {
            byte[] xmlByte = xmlString.getBytes("utf-8");
            ByteArrayInputStream byteInputStream = new ByteArrayInputStream(xmlByte);
            DocumentBuilder builder = factory.newDocumentBuilder();
            document = builder.parse(byteInputStream);

            // Use a Transformer for output
            TransformerFactory tFactory = TransformerFactory.newInstance();
            StreamSource stylesource = new StreamSource(new File(xslFile));
            Transformer transformer = tFactory.newTransformer(stylesource);

            DOMSource source = new DOMSource(document);
            StreamResult result = new StreamResult(outWriter);
            transformer.transform(source, result);
        } catch (TransformerConfigurationException tce) {
            // Error generated by the parser
            System.out.println("\n** Transformer Factory error");
            System.out.println("   " + tce.getMessage());

            // Use the contained exception, if any
            Throwable x = tce;

            if (tce.getException() != null) {
                x = tce.getException();
            }

            x.printStackTrace();
        } catch (TransformerException te) {
            // Error generated by the parser
            System.out.println("\n** Transformation error");
            System.out.println("   " + te.getMessage());

            // Use the contained exception, if any
            Throwable x = te;

            if (te.getException() != null) {
                x = te.getException();
            }

            x.printStackTrace();
        } catch (SAXException sxe) {
            // Error generated by this application
            // (or a parser-initialization error)
            Exception x = sxe;

            if (sxe.getException() != null) {
                x = sxe.getException();
            }

            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();
        } catch (IOException ioe) {
            // I/O error
            ioe.printStackTrace();
        }
        return outWriter.toString();
    }
    
    public String buildNewGroupMenu(){
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        Document document;
        StringWriter outWriter = new StringWriter();
        //factory.setNamespaceAware(true);
        //factory.setValidating(true);
        try {
            DocumentBuilder builder = factory.newDocumentBuilder();
            document = builder.parse(new File(fileURL));

            // Use a Transformer for output
            TransformerFactory tFactory = TransformerFactory.newInstance();
            StreamSource stylesource = new StreamSource(new File(xslGroupFile));
            Transformer transformer = tFactory.newTransformer(stylesource);

            DOMSource source = new DOMSource(document);
            StreamResult result = new StreamResult(outWriter);
            transformer.transform(source, result);
        } catch (TransformerConfigurationException tce) {
            // Error generated by the parser
            System.out.println("\n** Transformer Factory error");
            System.out.println("   " + tce.getMessage());

            // Use the contained exception, if any
            Throwable x = tce;

            if (tce.getException() != null) {
                x = tce.getException();
            }

            x.printStackTrace();
        } catch (TransformerException te) {
            // Error generated by the parser
            System.out.println("\n** Transformation error");
            System.out.println("   " + te.getMessage());

            // Use the contained exception, if any
            Throwable x = te;

            if (te.getException() != null) {
                x = te.getException();
            }

            x.printStackTrace();
        } catch (SAXException sxe) {
            // Error generated by this application
            // (or a parser-initialization error)
            Exception x = sxe;

            if (sxe.getException() != null) {
                x = sxe.getException();
            }

            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();
        } catch (IOException ioe) {
            // I/O error
            ioe.printStackTrace();
        }
        return outWriter.toString();
    }
    
    
    public String getMenuGroupForEdit(String oldMenu) {
        try {
            byte[] xmlByte = oldMenu.getBytes("utf-8");
            ByteArrayInputStream byteInputStream = new ByteArrayInputStream(xmlByte);
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dbBuilder = dbFactory.newDocumentBuilder();
            Document docNew = dbBuilder.parse(new File(fileURL));
            NodeList newDisplayList = docNew.getElementsByTagName("display");
            for(int i = 0; i < newDisplayList.getLength(); i++) {
                Node displayNode = newDisplayList.item(i);
                displayNode.setTextContent("0");
            }
            try {
                Document docOld = dbBuilder.parse(byteInputStream);
                docOld.getDocumentElement().normalize();
                NodeList nodeList = docOld.getElementsByTagName("menu");
                for(int i = 0; i < nodeList.getLength(); i++) {
                    Node nodeMenu = nodeList.item(i);
                    String id = nodeMenu.getAttributes().getNamedItem("id").getNodeValue();
                    NodeList childList = nodeMenu.getChildNodes();
                    for (int j = 0; j < childList.getLength(); j++) {
                        Node nodeMenuChild = childList.item(j);
                        if (("display").equals(nodeMenuChild.getNodeName())) {
                            NodeList nodeNewList = docNew.getElementsByTagName("menu");
                            for(int n = 0; n < nodeNewList.getLength(); n++) {
                                Node nodeNewMenu = nodeNewList.item(n);
                                if(id.equals(nodeNewMenu.getAttributes().getNamedItem("id").getNodeValue())) {
                                    NodeList menuNewNodesList = nodeNewMenu.getChildNodes();
                                    for(int m = 0; m < menuNewNodesList.getLength(); m++) {
                                        Node nodeNewMenuChild = menuNewNodesList.item(m);
                                        if (("display").equals(nodeNewMenuChild.getNodeName())) {
                                            nodeNewMenuChild.setTextContent(nodeMenuChild.getTextContent());
                                        }
                                    }
                                }
                            }
                        } else if(("sub_menu").equals(nodeMenuChild.getNodeName())) {
                            String submenuId = nodeMenuChild.getAttributes().getNamedItem("id").getNodeValue();
                            NodeList subMenuChildList = nodeMenuChild.getChildNodes();
                            for (int k = 0; k < subMenuChildList.getLength(); k++) {
                                Node nodeSubMenuChild = subMenuChildList.item(k);
                                if (("display").equals(nodeSubMenuChild.getNodeName())) {
                                    NodeList nodeNewList = docNew.getElementsByTagName("sub_menu");
                                    for(int n = 0; n < nodeNewList.getLength(); n++) {
                                        Node nodeNewMenu = nodeNewList.item(n);
                                        if (submenuId.equals(nodeNewMenu.getAttributes().getNamedItem("id").getNodeValue())) {
                                            NodeList menuNewNodesList = nodeNewMenu.getChildNodes();
                                            for (int m = 0; m < menuNewNodesList.getLength(); m++) {
                                                Node nodeNewMenuChild = menuNewNodesList.item(m);
                                                if (("display").equals(nodeNewMenuChild.getNodeName())) {
                                                    nodeNewMenuChild.setTextContent(nodeSubMenuChild.getTextContent());
                                                }
                                            }
                                        }
                                    }
                                } else if(("menu_element").equals(nodeSubMenuChild.getNodeName())){
                                    String elementId = nodeSubMenuChild.getAttributes().getNamedItem("id").getNodeValue();
                                    NodeList elementChildList = nodeSubMenuChild.getChildNodes();
                                    for (int l = 0; l < elementChildList.getLength(); l++) {
                                        Node nodeElementChild = elementChildList.item(l);
                                        if (("display").equals(nodeElementChild.getNodeName())) {
                                            NodeList nodeNewList = docNew.getElementsByTagName("menu_element");
                                            for(int n = 0; n < nodeNewList.getLength(); n++) {
                                                Node nodeNewMenu = nodeNewList.item(n);
                                                if (elementId.equals(nodeNewMenu.getAttributes().getNamedItem("id").getNodeValue())) {
                                                    NodeList menuNewNodesList = nodeNewMenu.getChildNodes();
                                                    for(int m = 0; m < menuNewNodesList.getLength(); m++) {
                                                        Node nodeNewMenuChild = menuNewNodesList.item(m);
                                                        if (("display").equals(nodeNewMenuChild.getNodeName())) {
                                                            nodeNewMenuChild.setTextContent(nodeElementChild.getTextContent());
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } catch (SAXException ex) {
                Logger.getLogger(GroupServlet.class.getName()).log(Level.SEVERE, null, ex);
            }
            DOMSource domSource = new DOMSource(docNew);
            StringWriter writer = new StringWriter();
            StreamResult result = new StreamResult(writer);
            TransformerFactory tf = TransformerFactory.newInstance();
            Transformer transformer = tf.newTransformer();
            transformer.transform(domSource, result);
            return buildMenu(writer.toString());
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(GroupServlet.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(GroupServlet.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GroupServlet.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerConfigurationException ex) {
            Logger.getLogger(GroupServlet.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(GroupServlet.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }
}

