# Sample ResourceBundle properties file
#{"Item Name","Account","Classification","Delete"};

0=Name
#view
1=View

#edit
2=Edit

#delete
3=Delete

#move
4=Move

5=Lock

6=Status

7=Traceability

8=Traceability(ies)

9=Request Change