# Sample ResourceBundle properties file
# to do add french to this
delete=&#1581;&#1584;&#1601;
view=&#1605;&#1588;&#1575;&#1607;&#1583;&#1607;
viewdetails=View Details
edit=&#1578;&#1581;&#1585;&#1610;&#1585;
grouplist= Groups List
userlist=Users List
doclist=Documents List
accountlist=Folders List
accountitemlist= Configuration Items List
businessclasslist= Business Classifications List
selectaccount=Select Folder

cancel=Cancel

confirmselection=Confirm Selection

foraccount=For Folder

searchtitle=Search Separator

searchdocument=Search Documents For

keyword=Keyword

executesearch=Search

bookmark=Bookmark Document

backtolist=&#1575;&#1604;&#1593;&#1608;&#1583;&#1607; &#1573;&#1604;&#1609; &#1575;&#1604;&#1602;&#1575;&#1574;&#1605;&#1577;

savebookmark=Save

doctitle=&#1573;&#1587;&#1605; &#1575;&#1604;&#1605;&#1587;&#1578;&#1606;&#1583;

bookmarktext=Bookmark Text

documentimage=Image

contact=Please Contact System Administrator
#View Document Details 
viewdocumentdetails=View

systemid=&#1578;&#1593;&#1585;&#1610;&#1601; &#1575;&#1604;&#1606;&#1592;&#1575;&#1605;

accountname=Folder Name

accountclass=Configuration Item

docdate=&#1578;&#1575;&#1585;&#1610;&#1582; &#1575;&#1604;&#1605;&#1587;&#1578;&#1606;&#1583;

facevalue=Face Value

createdby=Created By

creationdate=Creation Date

#Description de document
documentdescription=Document Description

viewbookmark=View Bookmark

groupName=Group

selectfolder = Select Folder

begindate = Begin Date

enddate = End Date

typelist= Document Types List

#move separator
move=Move

#move to folder
toaccount=To Folder

updatestatus=Update Status

updateok=Done

bookmarkfldr=Bookmark

Mark=Make

makeinfluence=Add Traceability

ok=OK

Influenced=Affected Item ID

Influencedby=This Item

alreadybaselined=Baselined

lastbaseline=Last Baseline

InfluenceType=Traceablility Type

InfluenceStatus=Save Status

tracabilitydirection=Traceability Direction

versionnumber=Version Number

showTraceability=Show Traceability(ies)

TraceabilityList=Traceability List

Open=View Document

trcname=Influenced Name

trcId=System Identification

InfType=Traceability Type

tracType=Traceability Direction

createdbyname=Created By Name


requestchange=Add Change Request

modifiedby=Modified By

reviewedby=Reviewed By

approvedby=Approved By

releasedate=Release Date

newlock=New Lock
savelock=Save Lock
locktype=Lock Type
locknote=Lock Note
viewlock=View Lock

notowner=Not Owner

configitemtype=&#1606;&#1608;&#1593; &#1575;&#1604;&#1605;&#1587;&#1578;&#1606;&#1583;