# Sample ResourceBundle properties file
deletedocument-areusure?=Delete document-Are you sure?
delete=Delete
attachexcel=attach excel file
attachbefore=Attach file before filling in form
doccreationstatus=Creation Status
selectimagefile=Select Document
selectpdffile=Select Document
selectwordfile=Select Document
selectexcelfile=Select Document
selectemlfile=Select Document
selecthtmlfile=Select Document
doctitle=&#1593;&#1606;&#1608;&#1575;&#1606; &#1575;&#1604;&#1605;&#1587;&#1578;&#1606;&#1583;
accntclass=Separator
year=Year
month=Month
day=Day
docdesc=&#1575;&#1604;&#1608;&#1589;&#1601;
facevalue=Face Value [If Money]
docdate=&#1578;&#1575;&#1585;&#1610;&#1582; &#1575;&#1604;&#1605;&#1587;&#1578;&#1606;&#1583;
noclass=* No classifications are attached to this folder. Go to "Bussiness Admin" menu to associate classifications.
cancel=Cancel
createnewdoc=Create New Document
selectclient=Select Client
attachment=attachement
savedoc=Save Document
attachimage=Attach File
attachpdf=Attach PDF File
attachhtml=Attach HTML File
attacheml=Attach EML file
attachword=Attach Word File
createnewimagedoc=Create New Image Document
createnewpdfdoc=Create New PDF Document
createnewworddoc=Create New Word Document
createnewexceldoc=Create New Excel Document
createnewhtmldoc=Create New Html Document
createnewoutlookdoc=Create New Outlook Document
archivedoc=Archive Document
updatedoc=Update Document
fillingfolder = Now Filing for Folder
updatingfolder = Now Updating for Folder
doneattaching = Done Attaching
docstatus = Document Archiving Status
docupdatestatus=Document Updating Status:
docclass = Classification
dockey = Key

modifiedby=Modified By

reviewedby=Reviewed By

approvedby=Approved By

releasedate=Release Date

version=Version Number

confirm=Confirm

configitemtype=&#1606;&#1608;&#1593; &#1575;&#1604;&#1605;&#1587;&#1578;&#1606;&#1583;