# Sample ResourceBundle properties file

viewdoc=View Document
moredetails=More Details
bookmark=Book Mark
unmark=Unmark
deny=Not Allowed
listendoc=Listen Document
delete=Delete
Mark=Make
edit=Edit

showbaseline=Show All Baselines

showlastbaseline=Show Last Baseline Only

alreadyapplied=Already Applied
